
// src/places.js

const places = [
    // Hyderabad
'Mumbai, Maharashtra',
'Colaba, Mumbai',
'Fort, Mumbai',
'Marine Lines, Mumbai',
'Churchgate, Mumbai',
'Bandra West, Mumbai',
'Bandra East, Mumbai',
'Khar, Mumbai',
'Santacruz, Mumbai',
'Juhu, Mumbai',
'Vile Parle, Mumbai',
'Andheri West, Mumbai',
'Andheri East, Mumbai',
'Versova, Mumbai',
'Malad, Mumbai',
'Goregaon, Mumbai',
'Borivali, Mumbai',
'Kandivali, Mumbai',
'Dahisar, Mumbai',
'Worli, Mumbai',
'Lower Parel, Mumbai',
'Prabhadevi, Mumbai',
'Dadar, Mumbai',
'Matunga, Mumbai',
'Sion, Mumbai',
'Chembur, Mumbai',
'Ghatkopar, Mumbai',
'Vikhroli, Mumbai',
'Powai, Mumbai',
'Mulund, Mumbai',
'Bhandup, Mumbai',
'Kurla, Mumbai',
'Kalina, Mumbai',
'Mahim, Mumbai',
'Wadala, Mumbai',
'Sewri, Mumbai',
'Parel, Mumbai',
'Byculla, Mumbai',
'Mazgaon, Mumbai',
'Grant Road, Mumbai',
'Tardeo, Mumbai',
'Malabar Hill, Mumbai',
'Walkeshwar, Mumbai',
'Breach Candy, Mumbai',
'Nariman Point, Mumbai',
'Cuffe Parade, Mumbai',
'Kalbadevi, Mumbai',
'Bhuleshwar, Mumbai',
'Charni Road, Mumbai',
'Girgaon, Mumbai',
'Dongri, Mumbai',
'Antop Hill, Mumbai',
'Govandi, Mumbai',
'Mankhurd, Mumbai',
'Trombay, Mumbai',
'Anushakti Nagar, Mumbai',
'Deonar, Mumbai',
'Tilak Nagar, Mumbai',
'Chunabhatti, Mumbai',
'Jogeshwari, Mumbai',
'Oshiwara, Mumbai',
'Marol, Mumbai',
'Saki Naka, Mumbai',
'Chandivali, Mumbai',
'Hiranandani Gardens, Mumbai',
'Jacob Circle, Mumbai',
'Agripada, Mumbai',
'Dharavi, Mumbai',
'Kalbadevi, Mumbai',
'Marine Drive, Mumbai',
'Sion East, Mumbai',
'Sion West, Mumbai',
'Matunga East, Mumbai',
'Matunga West, Mumbai',
'Dadar East, Mumbai',
'Dadar West, Mumbai',
'Prabhadevi, Mumbai',
'Worli Sea Face, Mumbai',
'Goregaon East, Mumbai',
'Goregaon West, Mumbai',
'Malad East, Mumbai',
'Malad West, Mumbai',
'Borivali East, Mumbai',
'Borivali West, Mumbai',
'Kandivali East, Mumbai',
'Kandivali West, Mumbai',
'Dahisar East, Mumbai',
'Dahisar West, Mumbai',
'Mulund East, Mumbai',
'Mulund West, Mumbai',
'Bhandup East, Mumbai',
'Bhandup West, Mumbai',
'Vikhroli East, Mumbai',
'Vikhroli West, Mumbai',
'Ghatkopar East, Mumbai',
'Ghatkopar West, Mumbai',
'Chembur East, Mumbai',
'Chembur West, Mumbai',
'Wadala East, Mumbai',
'Wadala West, Mumbai',
'Kurla East, Mumbai',
'Kurla West, Mumbai',
'Andheri MIDC, Mumbai',
'Jogeshwari East, Mumbai',
'Jogeshwari West, Mumbai',
'Delhi, National Capital Territory',
'Connaught Place, Delhi',
'Karol Bagh, Delhi',
'Hauz Khas, Delhi',
'Greater Kailash, Delhi',
'South Extension, Delhi',
'Vasant Kunj, Delhi',
'Vasant Vihar, Delhi',
'Dwarka, Delhi',
'Rohini, Delhi',
'Pitampura, Delhi',
'Lajpat Nagar, Delhi',
'Saket, Delhi',
'Janakpuri, Delhi',
'Rajouri Garden, Delhi',
'Defence Colony, Delhi',
'Mayur Vihar, Delhi',
'Paschim Vihar, Delhi',
'Kalkaji, Delhi',
'Nehru Place, Delhi',
'Shahdara, Delhi',
'Chandni Chowk, Delhi',
'Paharganj, Delhi',
'Old Delhi, Delhi',
'Daryaganj, Delhi',
'Civil Lines, Delhi',
'Model Town, Delhi',
'Ashok Vihar, Delhi',
'Shalimar Bagh, Delhi',
'Punjabi Bagh, Delhi',
'Patel Nagar, Delhi',
'Kirti Nagar, Delhi',
'Moti Nagar, Delhi',
'Tilak Nagar, Delhi',
'Subhash Nagar, Delhi',
'Vikaspuri, Delhi',
'Najafgarh, Delhi',
'Nangloi, Delhi',
'Bawana, Delhi',
'Narela, Delhi',
'Burari, Delhi',
'Kamla Nagar, Delhi',
'Sarita Vihar, Delhi',
'Jasola, Delhi',
'Okhla, Delhi',
'Malviya Nagar, Delhi',
'Green Park, Delhi',
'Safdarjung Enclave, Delhi',
'Chittaranjan Park, Delhi',
'East of Kailash, Delhi',
'New Friends Colony, Delhi',
'Mahipalpur, Delhi',
'Aerocity, Delhi',
'Munirka, Delhi',
'Katwaria Sarai, Delhi',
'R K Puram, Delhi',
'Chanakyapuri, Delhi',
'Jor Bagh, Delhi',
'Shanti Niketan, Delhi',
'Anand Niketan, Delhi',
'Golf Links, Delhi',
'Sundar Nagar, Delhi',
'Nizamuddin, Delhi',
'Sarojini Nagar, Delhi',
'Lodi Colony, Delhi',
'Pragati Vihar, Delhi',
'Mayapuri, Delhi',
'Naraina, Delhi',
'Hari Nagar, Delhi',
'Tagore Garden, Delhi',
'Ramesh Nagar, Delhi',
'Mukherjee Nagar, Delhi',
'G T B Nagar, Delhi',
'Hudson Lines, Delhi',
'Vijay Nagar, Delhi',
'Adarsh Nagar, Delhi',
'Azadpur, Delhi',
'Wazirpur, Delhi',
'Tri Nagar, Delhi',
'Shakti Nagar, Delhi',
'Keshav Puram, Delhi',
'Lawrence Road, Delhi',
'Kohat Enclave, Delhi',
'Mangolpuri, Delhi',
'Sultanpuri, Delhi',
'Anand Vihar, Delhi',
'Karkardooma, Delhi',
'Preet Vihar, Delhi',
'Laxmi Nagar, Delhi',
'Pandav Nagar, Delhi',
'Nirman Vihar, Delhi',
'Yamuna Vihar, Delhi',
'Bhajanpura, Delhi',
'Seelampur, Delhi',
'Welcome Colony, Delhi',
'Dilshad Garden, Delhi',
'Vivek Vihar, Delhi',
'Seemapuri, Delhi',
'Gandhi Nagar, Delhi',
'Krishna Nagar, Delhi',
'Geeta Colony, Delhi',
'Shastri Park, Delhi',
'Sadar Bazaar, Delhi',
'Kamla Market, Delhi',
'Mori Gate, Delhi',
'Tis Hazari, Delhi',
'Jhandewalan, Delhi',
'Rani Jhansi Road, Delhi',
'Barakhamba Road, Delhi',
'India Gate, Delhi',
'Panchsheel Park, Delhi',
'Greater Kailash I, Delhi',
'Greater Kailash II, Delhi',
'South Extension I, Delhi',
'South Extension II, Delhi',
'Hauz Khas Village, Delhi',
'Hauz Khas Enclave, Delhi',
'Vasant Enclave, Delhi',
'Dwarka Sector 1, Delhi',
'Dwarka Sector 7, Delhi',
'Dwarka Sector 10, Delhi',
'Rohini Sector 3, Delhi',
'Rohini Sector 7, Delhi',
'Rohini Sector 15, Delhi',
'Pitampura North, Delhi',
'Pitampura South, Delhi',
'Janakpuri East, Delhi',
'Janakpuri West, Delhi',
'Bangalore, Karnataka',
'Indira Nagar, Bangalore',
'Whitefield, Bangalore',
'Koramangala, Bangalore',
'Jayanagar, Bangalore',
'Malleswaram, Bangalore',
'Rajaji Nagar, Bangalore',
'Marathahalli, Bangalore',
'Sarjapur Road, Bangalore',
'Bellandur, Bangalore',
'KR Puram, Bangalore',
'Electronic City, Bangalore',
'HSR Layout, Bangalore',
'BTM Layout, Bangalore',
'JP Nagar, Bangalore',
'Banashankari, Bangalore',
'Hebbal, Bangalore',
'Yelahanka, Bangalore',
'Domlur, Bangalore',
'Ulsoor, Bangalore',
'MG Road, Bangalore',
'Brigade Road, Bangalore',
'Commercial Street, Bangalore',
'Richmond Town, Bangalore',
'Lavelle Road, Bangalore',
'Frazer Town, Bangalore',
'Cox Town, Bangalore',
'Cooke Town, Bangalore',
'Benson Town, Bangalore',
'Vasanth Nagar, Bangalore',
'Basavanagudi, Bangalore',
'Padmanabhanagar, Bangalore',
'Vijayanagar, Bangalore',
'Kengeri, Bangalore',
'RR Nagar, Bangalore',
'Nagarbhavi, Bangalore',
'Chandra Layout, Bangalore',
'Kammanahalli, Bangalore',
'Kalyan Nagar, Bangalore',
'RT Nagar, Bangalore',
'Sadashivanagar, Bangalore',
'Sanjay Nagar, Bangalore',
'Banaswadi, Bangalore',
'Horamavu, Bangalore',
'Bannerghatta Road, Bangalore',
'Kanakapura Road, Bangalore',
'Mysore Road, Bangalore',
'Tumkur Road, Bangalore',
'Old Madras Road, Bangalore',
'Hosur Road, Bangalore',
'Bommanahalli, Bangalore',
'Bommasandra, Bangalore',
'Chandapura, Bangalore',
'Shanti Nagar, Bangalore',
'Wilson Garden, Bangalore',
'Ejipura, Bangalore',
'Murugeshpalya, Bangalore',
'Jeevan Bheema Nagar, Bangalore',
'Kadugodi, Bangalore',
'Varthur, Bangalore',
'Kundalahalli, Bangalore',
'Brookefield, Bangalore',
'Hoodi, Bangalore',
'Panathur, Bangalore',
'Ramamurthy Nagar, Bangalore',
'Kasturi Nagar, Bangalore',
'CV Raman Nagar, Bangalore',
'Sahakara Nagar, Bangalore',
'Vidyaranyapura, Bangalore',
'Nelamangala, Bangalore',
'Magadi Road, Bangalore',
'HBR Layout, Bangalore',
'OMBR Layout, Bangalore',
'New BEL Road, Bangalore',
'Dollars Colony, Bangalore',
'Giri Nagar, Bangalore',
'Kathriguppe, Bangalore',
'Chamarajpet, Bangalore',
'Basaveshwaranagar, Bangalore',
'Lingarajapuram, Bangalore',
'Mahalakshmi Layout, Bangalore',
'Nandini Layout, Bangalore',
'Shivaji Nagar, Bangalore',
'Seshadripuram, Bangalore',
'Cunningham Road, Bangalore',
'Langford Town, Bangalore',
'Ashok Nagar, Bangalore',
'Victoria Layout, Bangalore',
'Austin Town, Bangalore',
'Halasuru, Bangalore',
'Old Airport Road, Bangalore',
'Harlur, Bangalore',
'Kasavanahalli, Bangalore',
'Begur, Bangalore',
'Gottigere, Bangalore',
'Hulimavu, Bangalore',
'Arekere, Bangalore',
'Uttarahalli, Bangalore',
'Subramanyapura, Bangalore',
'Girinagar, Bangalore',
'Hanumanthanagar, Bangalore',
'Munnekollal, Bangalore',
'Thubarahalli, Bangalore',
'Balagere, Bangalore',
'Jakkur, Bangalore',
'Bellary Road, Bangalore',
'Chikkalasandra, Bangalore',
'Kumaraswamy Layout, Bangalore',
'Anjanapura, Bangalore',
'Rajarajeshwari Nagar, Bangalore',
'Hongasandra, Bangalore',
'Madiwala, Bangalore',
'Singasandra, Bangalore',
'Kalena Agrahara, Bangalore',
'Bilekahalli, Bangalore',
'Hesaraghatta, Bangalore',
'Channasandra, Bangalore',
'Kaggadasapura, Bangalore',
'Vignan Nagar, Bangalore',
'Malleshpalya, Bangalore',
'Rachenahalli, Bangalore',
'Kodigehalli, Bangalore',
'T Dasarahalli, Bangalore',
'Byatarayanapura, Bangalore',
'Yelachenahalli, Bangalore',
'Konanakunte, Bangalore',
'Kothanur, Bangalore',
'Green Glen Layout, Bangalore',
'NRI Layout, Bangalore',
'TC Palya, Bangalore',
'Battarahalli, Bangalore',
'Medahalli, Bangalore',
'Avalahalli, Bangalore',
'Chikkabanavara, Bangalore',
'Abbigere, Bangalore',
'Annapurneshwari Nagar, Bangalore',
'Laggere, Bangalore',
'Kamakshipalya, Bangalore',
'Vyalikaval, Bangalore',
'Palace Guttahalli, Bangalore',
'High Grounds, Bangalore',
'St. Johns Road, Bangalore',
'Neelasandra, Bangalore',
'Sudhama Nagar, Bangalore',
'Cottonpet, Bangalore',
'Gandhinagar, Bangalore',
'Chickpet, Bangalore',
'Sampangiram Nagar, Bangalore',
'Bharatinagar, Bangalore',
'Residency Road, Bangalore',
'Infantry Road, Bangalore',
'Kaval Bairasandra, Bangalore',
'Sultanpalya, Bangalore',
'Gangenahalli, Bangalore',
'Mathikere, Bangalore',
'HMT Layout, Bangalore',
'Gokula Extension, Bangalore',
'Maruthi Seva Nagar, Bangalore',
'Bhoopasandra, Bangalore',
'New Thippasandra, Bangalore',
'HAL 2nd Stage, Bangalore',
'HAL 3rd Stage, Bangalore',
'Kodihalli, Bangalore',
'Kartik Nagar, Bangalore',
'Dodda Nekkundi, Bangalore',
'Vibhutipura, Bangalore',
'Vimanapura, Bangalore',
'Sarjapur, Bangalore',
'Hadosiddapura, Bangalore',
'Choodasandra, Bangalore',
'Rayasandra, Bangalore',
'Akshaya Nagar, Bangalore',
'Talaghattapura, Bangalore',
'Hemmigepura, Bangalore',
'Judicial Layout, Bangalore',
'Hosakerehalli, Bangalore',
'Srinivaspura, Bangalore',
'Bapuji Nagar, Bangalore',
'Jagajeevanram Nagar, Bangalore',
'Padarayanapura, Bangalore',
'Chamrajpet, Bangalore',
'Azad Nagar, Bangalore',
'Kalasipalya, Bangalore',
'Dharmaraya Swamy Temple Area, Bangalore',
'Suddagunte Palya, Bangalore',
'Agara, Bangalore',
'Jakkasandra, Bangalore',
'Venkateshpura, Bangalore',
'Pulikeshi Nagar, Bangalore',
'Hoysala Nagar, Bangalore',
'Richards Town, Bangalore',
'Hennur Road, Bangalore',
'Nrupathunga Road, Bangalore',
'Cubbon Park, Bangalore',
'Museum Road, Bangalore',
'Church Street, Bangalore',
'Kasturba Road, Bangalore',
'Vittal Mallya Road, Bangalore',
'JC Road, Bangalore',
'Bannerghatta, Bangalore',
'Kadubeesanahalli, Bangalore',
'Kaikondrahalli, Bangalore',
'Carmelaram, Bangalore',
'Tavarekere, Bangalore',
'Kumbalgodu, Bangalore',
'Sompura, Bangalore',
'Huskur, Bangalore',
'Hebbagodi, Bangalore',
'Narasapura, Bangalore',
'Rajankunte, Bangalore',
'Chikkajala, Bangalore',
'Bagaluru, Bangalore',
'Dommasandra, Bangalore',
'Gunjur, Bangalore',
'Chikkathoguru, Bangalore',
'Kachamaranahalli, Bangalore',
'Mallasandra, Bangalore',
'Soladevanahalli, Bangalore',
'Thammenahalli, Bangalore',
'Meenakunte, Bangalore',
'Chikkabettahalli, Bangalore',
'Kattigenahalli, Bangalore',
'Sadenahalli, Bangalore',
'Hunasamaranahalli, Bangalore',
'Chokkanahalli, Bangalore',
'Nagawara, Bangalore',
'Hegde Nagar, Bangalore',
'Manyata Tech Park, Bangalore',
'Amruthahalli, Bangalore',
'Coffee Board Layout, Bangalore',
'GKVK Layout, Bangalore',
'Telecom Layout, Bangalore',
'Judicial Colony, Bangalore',
'Tata Nagar, Bangalore',
'Anand Nagar, Bangalore',
'Cholanayakanahalli, Bangalore',
'Sampigehalli, Bangalore',
'Horamavu Agara, Bangalore',
'Kalkere, Bangalore',
'Nallurhalli, Bangalore',
'Immadihalli, Bangalore',
'Channasandra Layout, Bangalore',
'Pattandur Agrahara, Bangalore',
'Hagadur, Bangalore',
'Sai Layout, Bangalore',
'Seegehalli, Bangalore',
'Basapura, Bangalore',
'Hosa Road, Bangalore',
'Kudlu Gate, Bangalore',
'AECS Layout, Bangalore',
'ITI Layout, Bangalore',
'Whitefield Road, Bangalore',
'Hope Farm Junction, Bangalore',
'Kadugodi Plantation, Bangalore',
'Channasandra Village, Bangalore',
'Electronic City Phase 1, Bangalore',
'Electronic City Phase 2, Bangalore',
'Neeladri Nagar, Bangalore',
'Konappana Agrahara, Bangalore',
'Doddathoguru, Bangalore',
'Shikaripalya, Bangalore',
'Huskur Gate, Bangalore',
'Veerasandra, Bangalore',
'Naganathapura, Bangalore',
'Parappana Agrahara, Bangalore',
'Beratena Agrahara, Bangalore',
'Mangammanapalya, Bangalore',
'Garvebhavi Palya, Bangalore',
'Panduranga Nagar, Bangalore',
'Devarabisanahalli, Bangalore',
'Kariyammana Agrahara, Bangalore',
'Bhoganahalli, Bangalore',
'Raghuvanahalli, Bangalore',
'Vajarahalli, Bangalore',
'Kambipura, Bangalore',
'Channenahalli, Bangalore',
'Kadabagere, Bangalore',
'Seegehalli Village, Bangalore',
'Kaggalipura, Bangalore',
'Nagegowdanapalya, Bangalore',
'Nettigere, Bangalore',
'Guddahatti, Bangalore',
'Chudenapura, Bangalore',
'Alahalli, Bangalore',
'Thippagondanahalli, Bangalore',
'Madanayakanahalli, Bangalore',
'Makali, Bangalore',
'Nagarur, Bangalore',
'Dasanapura, Bangalore',
'Adakamaranahalli, Bangalore',
'Huralichikkanahalli, Bangalore',
'Lakshmipura, Bangalore',
'Lingadheeranahalli, Bangalore',
'Andrahalli, Bangalore',
'Peenya Industrial Area, Bangalore',
'Chikkabidarakallu, Bangalore',
'Karihobanahalli, Bangalore',
'Ganigarahalli, Bangalore',
'Thotada Guddadhalli, Bangalore',
'Kachohalli, Bangalore',
'Heggadahalli, Bangalore',
'Somashetti Halli, Bangalore',
'Sonnenahalli, Bangalore',
'Ullal, Bangalore',
'Jnana Bharathi, Bangalore',
'Mariyappana Palya, Bangalore',
'Pattanagere, Bangalore',
'Kengeri Satellite Town, Bangalore',
'Dubasipalya, Bangalore',
'Mallathahalli, Bangalore',
'Bharath Nagar, Bangalore',
'BEL Layout, Bangalore',
'Anupadahalli, Bangalore',
'Chikkamaranahalli, Bangalore',
'Siddihosakote, Bangalore',
'Kanaswadi, Bangalore',
'Dodderi, Bangalore',
'Madavara, Bangalore',
'Huruliborasandra, Bangalore',
'Shivakote, Bangalore',
'Iggalur, Bangalore',
'Singanayakanahalli, Bangalore',
'Kakolu, Bangalore',
'Bilijaji, Bangalore',
'Byatha, Bangalore',
'Kodathi, Bangalore',
'Sulikunte, Bangalore',
'Muthanallur, Bangalore',
'Gattahalli, Bangalore',
'Chikkanahalli, Bangalore',
'Ambedkar Nagar, Bangalore',
'Chikkanagamangala, Bangalore',
'Bhattarahalli, Bangalore',
'Anugondanahalli, Bangalore',
'Kannamangala, Bangalore',
'Cheemasandra, Bangalore',
'Avalahalli Village, Bangalore',
'Bidrahalli, Bangalore',
'Mandur, Bangalore',
'Adur, Bangalore',
'Hirandahalli, Bangalore',
'Kithaganur, Bangalore',
'Halehalli, Bangalore',
'Rampura, Bangalore',
'Huskur Village, Bangalore',
'Mutsandra, Bangalore',
'Vaderahalli, Bangalore',
'Chikkagubbi, Bangalore',
'Byrathi, Bangalore',
'Bande Bommasandra, Bangalore',
'Gantiganahalli, Bangalore',
'Challahalli, Bangalore',
'Kodipalya Village, Bangalore',
'Vaderamanchanahalli, Bangalore',
'Haralur, Bangalore',
'Mylasandra, Bangalore',
'Lingadheeranahalli Village, Bangalore',
'Kenchanapura, Bangalore',
'Ganakal, Bangalore',
'Kothanoor, Bangalore',
'Chikkanayakanahalli, Bangalore',
'Ittamadu, Bangalore',
'Bileshivale, Bangalore',
'Chikkakannalli, Bangalore',
'Bellahalli, Bangalore',
'Jnanabharathi, Bangalore',
'Kannahalli, Bangalore',
'Srigandhada Kaval, Bangalore',
'Kadugondanahalli, Bangalore',
'Huvinayakanahalli, Bangalore',
'Chikkasandra, Bangalore',
'Bagalakunte, Bangalore',
'Nagasandra, Bangalore',
'Narasipura, Bangalore',
'Mallasandra Village, Bangalore',
'Chikkabanaswadi, Bangalore',
'Veerannapalya, Bangalore',
'Arabic College, Bangalore',
'Venkateshpuram, Bangalore',
'Tannery Road, Bangalore',
'Periyar Nagar, Bangalore',
'DJ Halli, Bangalore',
'Devara Jeevanahalli, Bangalore',
'Dooravani Nagar, Bangalore',
'ITPL, Bangalore',
'Chikka Banaswadi, Bangalore',
'Subramanyanagar, Bangalore',
'Milk Colony, Bangalore',
'Palace Grounds, Bangalore',
'Sankey Road, Bangalore',
'Gayathri Nagar, Bangalore',
'Prakash Nagar, Bangalore',
'Sri Chowdeshwari Nagar, Bangalore',
'Armane Nagar, Bangalore',
'Hanumanthappa Layout, Bangalore',
'Kumara Park West, Bangalore',
'Kumara Park East, Bangalore',
'Race Course Road, Bangalore',
'Serpentine Road, Bangalore',
'Okalipuram, Bangalore',
'City Railway Station Area, Bangalore',
'Upparpet, Bangalore',
'BVK Iyengar Road, Bangalore',
'SP Road, Bangalore',
'KR Market, Bangalore',
'Mamulpet, Bangalore',
'Nagarathpet, Bangalore',
'JC Nagar, Bangalore',
'Maruthi Nagar, Bangalore',
'RMV Extension, Bangalore',
'Dollars Layout, Bangalore',
'AECS Layout Brookefield, Bangalore',
'Marathahalli Village, Bangalore',
'HAL Airport Area, Bangalore',
'ISRO Layout, Bangalore',
'Shakambari Nagar, Bangalore',
'Siddapura, Bangalore',
'Nandidurga Road, Bangalore',
'Jayamahal, Bangalore',
'Binnypet, Bangalore',
'Magadi, Bangalore',
'Chikkapete, Bangalore',
'Kalyana Nagar, Bangalore',
'Pai Layout, Bangalore',
'Mahaganapathi Nagar, Bangalore',
'Hanumantha Nagar, Bangalore',
'Girinagar Extension, Bangalore',
'Srinivas Nagar, Bangalore',
'Bank Colony, Bangalore',
'BEML Layout, Bangalore',
'HRBR Layout, Bangalore',
'PNS Layout, Bangalore',
'Coconut Grove Layout, Bangalore',
'Nagashetty Halli, Bangalore',
'RMV 2nd Stage, Bangalore',
'Devinagar, Bangalore',
'Lottegollahalli, Bangalore',
'Maruthi Layout, Bangalore',
'Bhuvaneswari Nagar, Bangalore',
'Hebbal Kempapura, Bangalore',
'Amruthnagar, Bangalore',
'Byadarahalli, Bangalore',
'Kirloskar Layout, Bangalore',
'Marenahalli, Bangalore',
'Thyagarajanagar, Bangalore',
'NR Colony, Bangalore',
'Byrasandra, Bangalore',
'Jayanagar East, Bangalore',
'Tilak Nagar, Bangalore',
'Raghavendra Nagar, Bangalore',
'Shankarapuram, Bangalore',
'Kaveri Nagar, Bangalore',
'Mavalli, Bangalore',
'Lalbagh, Bangalore',
'Sunkenahalli, Bangalore',
'Visvesvarapuram, Bangalore',
'Hanumanth Nagar Extension, Bangalore',
'Kalappa Layout, Bangalore',
'Kempegowda Nagar, Bangalore',
'Swimming Pool Extension, Bangalore',
'Kanakanagar, Bangalore',
'VHBCS Layout, Bangalore',
'Guttahalli, Bangalore',
'Malleshwaram West, Bangalore',
'Srirampuram, Bangalore',
'Rajamahal Vilas, Bangalore',
'Kadu Malleshwara, Bangalore',
'Subramanya Nagar, Bangalore',
'Vyalikaval Extension, Bangalore',
'Dollars Scheme Colony, Bangalore',
'Canara Bank Colony, Bangalore',
'Chikkammanahalli, Bangalore',
'Hombegowda Nagar, Bangalore',
'Lakkasandra, Bangalore',
'Adugodi, Bangalore',
'Bendre Nagar, Bangalore',
'Kadirenahalli, Bangalore',
'Karisandra, Bangalore',
'Yediyur, Bangalore',
'Vidyapeetha, Bangalore',
'Ashok Nagar Extension, Bangalore',
'Domlur Layout, Bangalore',
'Stage 2 Indiranagar, Bangalore',
'Defence Colony Indiranagar, Bangalore',
'Michael Palya, Bangalore',
'Rustam Bagh Layout, Bangalore',
'Vibhutipura Extension, Bangalore',
'LIC Colony, Bangalore',
'Sri Venkateshwara Nagar, Bangalore',
'Konena Agrahara, Bangalore',
'Srinivas Colony, Bangalore',
'HAL Layout, Bangalore',
'BTM 1st Stage, Bangalore',
'BTM 2nd Stage, Bangalore',
'Madivala Lake, Bangalore',
'NS Palya, Bangalore',
'Gurappanapalya, Bangalore',
'Suddaguntepalya Extension, Bangalore',
'Bannerghatta Main Road, Bangalore',
'Dollars Colony JP Nagar, Bangalore',
'Royal County, Bangalore',
'Gottigere Extension, Bangalore',
'Meenakshi Layout, Bangalore',
'Anjanapura Township, Bangalore',
'Chunchaghatta, Bangalore',
'Vasanthapura, Bangalore',
'Turahalli, Bangalore',
'Hemmigepura Extension, Bangalore',
'Banashankari 6th Stage, Bangalore',
'Lingambudhi Palya, Bangalore',
'Talaghattapura Extension, Bangalore',
'Vaddarapalya, Bangalore',
'Kengeri Hobli, Bangalore',
'Ganapathipura, Bangalore',
'Chikka Togur, Bangalore',
'Gubbalala, Bangalore',
'Subramanyapura Extension, Bangalore',
'Thurahalli, Bangalore',
'Chandra Nagar, Bangalore',
'Kamala Nagar, Bangalore',
'Bhuvaneshwari Nagar, Bangalore',
'Freedom Fighters Colony, Bangalore',
'LBS Nagar, Bangalore',
'Dayananda Nagar, Bangalore',
'RPC Layout, Bangalore',
'Maruthi HBCS Layout, Bangalore',
'Kaveri Pura, Bangalore',
'Muneshwara Nagar, Bangalore',
'Shakthi Ganapathi Nagar, Bangalore',
'Kalyana Nagar, Bangalore',
'Kamakya Layout, Bangalore',
'BSK 3rd Stage, Bangalore',
'Poorna Pragna Layout, Bangalore',
'Avalahalli Extension, Bangalore',
'Dwaraka Nagar, Bangalore',
'Hosakerehalli Extension, Bangalore',
'Byraveshwara Nagar, Bangalore',
'Deepanjali Nagar, Bangalore',
'Kempapura Agrahara, Bangalore',
'Moodalapalya, Bangalore',
'BCC Layout, Bangalore',
'Chandra Layout Extension, Bangalore',
'Gangondanahalli, Bangalore',
'Nayandahalli, Bangalore',
'Jnana Ganga Nagar, Bangalore',
'Malagala, Bangalore',
'Annapurneshwari Layout, Bangalore',
'GKW Layout, Bangalore',
'KPA Block, Bangalore',
'Bharat Nagar, Bangalore',
'Syndicate Bank Colony, Bangalore',
'Srinidhi Layout, Bangalore',
'Nrupathunga Nagar, Bangalore',
'Manjunatha Nagar, Bangalore',
'Bapuji Layout, Bangalore',
'Chennammanakere Achukattu, Bangalore',
'Kathriguppe Extension, Bangalore',
'Banashankari 2nd Stage, Bangalore',
'Banashankari 3rd Stage, Bangalore',
'Srinivasapura Extension, Bangalore',
'Raghavendra Block, Bangalore',
'Banashankari 5th Stage, Bangalore',
'Vidyamanya Nagar, Bangalore',
'Shakambari Layout, Bangalore',
'Jarganahalli, Bangalore',
'Kanakadasa Nagar, Bangalore',
'Puttenahalli, Bangalore',
'JP Nagar 7th Phase, Bangalore',
'JP Nagar 8th Phase, Bangalore',
'JP Nagar 9th Phase, Bangalore',
'Sarakki, Bangalore',
'Shakuntala Nagar, Bangalore',
'Brindavan Nagar, Bangalore',
'Mico Layout, Bangalore',
'Mahalakshmi Puram, Bangalore',
'West of Chord Road, Bangalore',
'Shankar Nagar, Bangalore',
'Lorry Stand Godown, Bangalore',
'KHB Colony, Bangalore',
'Kamakshipalya Extension, Bangalore',
'Basaveshwara Nagar Extension, Bangalore',
'Mohan Kumar Nagar, Bangalore',
'Kirloskar Colony, Bangalore',
'Saraswathipuram, Bangalore',
'Agrahara Dasarahalli, Bangalore',
'Kaveripura, Bangalore',
'Shivapura, Bangalore',
'Peenya 2nd Stage, Bangalore',
'Nethaji Layout, Bangalore',
'HMT Housing Colony, Bangalore',
'Chokkasandra, Bangalore',
'Jalahalli East, Bangalore',
'Jalahalli West, Bangalore',
'MS Palya, Bangalore',
'Gangamma Circle, Bangalore',
'MEI Layout, Bangalore',
'Lakshmidevi Nagar, Bangalore',
'Nandini Layout Extension, Bangalore',
'Siddhartha Nagar, Bangalore',
'Laggere Extension, Bangalore',
'Parvathi Nagar, Bangalore',
'Srigandha Kaval, Bangalore',
'Jarakabande Kaval, Bangalore',
'Kariyana Palya, Bangalore',
'Handrahalli, Bangalore',
'Chikkasandra Extension, Bangalore',
'Singapura, Bangalore',
'Air Force Station Yelahanka, Bangalore',
'CRPF Campus, Bangalore',
'Jalahalli Village, Bangalore',
'Kenchanahalli, Bangalore',
'Chowdeshwari Layout, Bangalore',
'Yelahanka New Town, Bangalore',
'Anantapur, Bangalore',
'Yelahanka Old Town, Bangalore',
'Kogilu, Bangalore',
'Agrahara, Bangalore',
'Allalasandra, Bangalore',
'Chikka Bettahalli, Bangalore',
'Kendriya Vihar, Bangalore',
'Venkateshwara Nagar, Bangalore',
'Attur Layout, Bangalore',
'Yelahanka Satellite Town, Bangalore',
'GKVK Campus, Bangalore',
'Byatarayanapura Extension, Bangalore',
'Judicial Layout Yelahanka, Bangalore',
'Yelahanka Industrial Area, Bangalore',
'Bagalur Main Road, Bangalore',
'Dwarakanagar, Bangalore',
'Rajanukunte, Bangalore',
'Avalahalli Yelahanka, Bangalore',
'Anantapura, Bangalore',
'Puttenahalli Yelahanka, Bangalore',
'Srinivasapura Yelahanka, Bangalore',
'Nehru Nagar, Bangalore',
'Kamila Nehru Extension, Bangalore',
'Vasudevapura, Bangalore',
'Sonappa Layout, Bangalore',
'Chamundeshwari Layout, Bangalore',
'M Vishweshwaraiah Nagar, Bangalore',
'Kannur, Bangalore',
'Alur, Bangalore',
'Honnenahalli, Bangalore',
'Vaderahalli Yelahanka, Bangalore',
'Chikkabommasandra, Bangalore',
'Shivaramkaranth Nagar, Bangalore',
'Telecom Layout Yelahanka, Bangalore',
'Gandhi Nagar Yelahanka, Bangalore',
'Adityanagar, Bangalore',
'BSF Campus, Bangalore',
'RK Hegde Nagar, Bangalore',
'Narayanapura, Bangalore',
'Hennur Bande, Bangalore',
'Hennur Gardens, Bangalore',
'Hennur Main Road, Bangalore',
'Ashirvad Colony, Bangalore',
'Horamavu Banaswadi, Bangalore',
'P and T Layout, Bangalore',
'Chelekare, Bangalore',
'Babusapalya, Bangalore',
'Vijaya Bank Colony, Bangalore',
'Brindavan Layout, Bangalore',
'Vinayaka Nagar, Bangalore',
'NRI Layout Kalkere, Bangalore',
'Arkavathy Layout, Bangalore',
'Thanisandra Main Road, Bangalore',
'RK Nagar, Bangalore',
'Asha Township, Bangalore',
'Sampige Layout, Bangalore',
'Coconut Garden, Bangalore',
'Geddalahalli, Bangalore',
'Kothanur Extension, Bangalore',
'Chokkanahalli Extension, Bangalore',
'Pillanna Garden, Bangalore',
'Tannery Road Extension, Bangalore',
'Richards Town Extension, Bangalore',
'MM Layout, Bangalore',
'Govindapura, Bangalore',
'Nagavara Village, Bangalore',
'HBR 1st Block, Bangalore',
'HBR 2nd Block, Bangalore',
'HBR 3rd Block, Bangalore',
'Kadugondanahalli Extension, Bangalore',
'Venkateshpura Extension, Bangalore',
'Lingarajapuram Extension, Bangalore',
'St Thomas Town, Bangalore',
'Kammanahalli Extension, Bangalore',
'Kacharakanahalli, Bangalore',
'Jalvayu Vihar, Bangalore',
'Kalyan Nagar Extension, Bangalore',
'Banaswadi Main Road, Bangalore',
'Subbayanapalya, Bangalore',
'MS Nagar, Bangalore',
'Ex-Servicemen Colony, Bangalore',
'Chinnappa Layout, Bangalore',
'Dodda Gubbi, Bangalore',
'Nagondanahalli, Bangalore',
'Shanthi Layout, Bangalore',
'Anandapura, Bangalore',
'TC Palya Main Road, Bangalore',
'Old Baiyappanahalli, Bangalore',
'New Baiyappanahalli, Bangalore',
'Krishnaraja Puram Extension, Bangalore',
'A Narayanapura, Bangalore',
'Udaya Nagar, Bangalore',
'Tin Factory, Bangalore',
'Pai Layout KR Puram, Bangalore',
'Garden City, Bangalore',
'Devasandra, Bangalore',
'HAL Layout, Bangalore',
'Ayyappa Nagar, Bangalore',
'B Narayanapura, Bangalore',
'Mahadevapura Industrial Area, Bangalore',
'Garudachar Palya, Bangalore',
'EPIP Zone, Bangalore',
'Chinnaswamy Layout, Bangalore',
'BEML Layout Brookefield, Bangalore',
'Kundalahalli Colony, Bangalore',
'GM Palya, Bangalore',
'Basavanna Nagar, Bangalore',
'Doddanekundi, Bangalore',
'Thigalarapalya, Bangalore',
'Hoodi Village, Bangalore',
'Sadaramangala, Bangalore',
'Pattandur Agrahara Extension, Bangalore',
'Whitefield Main Road, Bangalore',
'Vinayaka Layout, Bangalore',
'Chansandra, Bangalore',
'Nagappa Reddy Layout, Bangalore',
'Yeshwanthpur Industrial Suburb, Bangalore',
'Goraguntepalya, Bangalore',
'Nandini Layout Industrial Area, Bangalore',
'Tumkur Road Industrial Area, Bangalore',
'Rajajinagar Industrial Area, Bangalore',
'WOC Road, Bangalore',
'Modi Garden, Bangalore',
'Dr Shivaram Karanth Nagar, Bangalore',
'BHEL Layout, Bangalore',
'Manjunatha Layout, Bangalore',
'Shankarappa Layout, Bangalore',
'Vrushabhavathi Nagar, Bangalore',
'Chandra Layout Main Road, Bangalore',
'Income Tax Layout, Bangalore',
'Vijayanagar Extension, Bangalore',
'RPC Layout Vijayanagar, Bangalore',
'Maruthi Nagar Vijayanagar, Bangalore',
'MC Layout, Bangalore',
'Hoshalli Extension, Bangalore',
'Bapuji Nagar Vijayanagar, Bangalore',
'Kamala Nagar Extension, Bangalore',
'Basaveshwara Nagar 3rd Stage, Bangalore',
'KHB Colony Extension, Bangalore',
'Sharada Colony, Bangalore',
'Agrahara Layout, Bangalore',
'Bovi Colony, Bangalore',
'Kirloskar Layout Vijayanagar, Bangalore',
'Saraswati Nagar, Bangalore',
'Marenahalli Extension, Bangalore',
'Vinayaka Layout Vijayanagar, Bangalore',
'Prashanth Nagar, Bangalore',
'AGS Layout, Bangalore',
'NGEF Layout, Bangalore',
'Sadashiva Nagar Extension, Bangalore',
'Palace Orchard, Bangalore',
'Ali Asker Road, Bangalore',
'Benson Cross Road, Bangalore',
'Cleveland Town, Bangalore',
'Pottery Town, Bangalore',
'RS Palya, Bangalore',
'Jeevanahalli, Bangalore',
'Sarvabhouma Nagar, Bangalore',
'ISKCON Temple Area, Bangalore',
'Pipeline Road, Bangalore',
'JC Nagar Extension, Bangalore',
'Kurubarahalli, Bangalore',
'Mattadahalli, Bangalore',
'Vasantappa Block, Bangalore',
'Dattatreya Temple Area, Bangalore',
'Malleshwaram 8th Main, Bangalore',
'Malleshwaram 11th Cross, Bangalore',
'LIC Colony Yeshwanthpur, Bangalore',
'BEL Road, Bangalore',
'APMC Yard, Bangalore',
'RMC Yard, Bangalore',
'Dollars Colony Yeshwanthpur, Bangalore',
'Gokul Extension, Bangalore',
'Muniswara Nagar, Bangalore',
'Brindavan Nagar Yeshwanthpur, Bangalore',
'Ashokpuram, Bangalore',
'Devaiah Park, Bangalore',
'Gayathri Nagar Extension, Bangalore',
'Sampangiram Nagar Extension, Bangalore',
'Cubbonpet, Bangalore',
'Shivananda Nagar, Bangalore',
'Hanumanthappa Nagar, Bangalore',
'Kumbarpet, Bangalore',
'Akkipet, Bangalore',
'NR Road, Bangalore',
'Avenue Road, Bangalore',
'Thigalarpet, Bangalore',
'Balepet, Bangalore',
'Pete Chennappa, Bangalore',
'SKR Market, Bangalore',
'Ranasinghpet, Bangalore',
'Sultanpet, Bangalore',
'Journalist Colony, Bangalore',
'Minerva Circle, Bangalore',
'Mission Road, Bangalore',
'Sampige Road, Bangalore',
'Malleshwaram Circle, Bangalore',
'Vyalikaval Main Road, Bangalore',
'Bashyam Circle, Bangalore',
'Bhashyam Nagar, Bangalore',
'TATA Nagar, Bangalore',
'Shankar Mutt, Bangalore',
'Chikkamaranahalli Extension, Bangalore',
'Hanumanthapur, Bangalore',
'Raghaveendra Nagar, Bangalore',
'Cottonpet Extension, Bangalore',
'Kalasipalyam Extension, Bangalore',
'Vinayaka Circle, Bangalore',
'Hanumanth Nagar Main Road, Bangalore',
'Ashok Nagar Main Road, Bangalore',
'Museum Cross Road, Bangalore',
'Richmond Circle, Bangalore',
'Double Road, Bangalore',
'Lalbagh Main Road, Bangalore',
'JC Road Extension, Bangalore',
'KH Road, Bangalore',
'Shanthinagar Bus Stand, Bangalore',
'Siddapura Extension, Bangalore',
'Domlur 2nd Stage, Bangalore',
'Amarjyothi Layout, Bangalore',
'Srinivas Colony, Bangalore',
'HAL 2nd Stage Extension, Bangalore',
'New Thippasandra Extension, Bangalore',
'GM Palya Extension, Bangalore',
'Kundalahalli Gate, Bangalore',
'Marathahalli Bridge, Bangalore',
'Chennai, Tamil Nadu',
'T. Nagar, Chennai',
'Adyar, Chennai',
'Anna Nagar, Chennai',
'Mylapore, Chennai',
'Velachery, Chennai',
'Nungambakkam, Chennai',
'Alwarpet, Chennai',
'Besant Nagar, Chennai',
'Guindy, Chennai',
'Kodambakkam, Chennai',
'Teynampet, Chennai',
'Egmore, Chennai',
'Royapettah, Chennai',
'Kilpauk, Chennai',
'Chetpet, Chennai',
'Vadapalani, Chennai',
'Koyambedu, Chennai',
'Ashok Nagar, Chennai',
'West Mambalam, Chennai',
'Saidapet, Chennai',
'Chromepet, Chennai',
'Tambaram, Chennai',
'Porur, Chennai',
'Poonamallee, Chennai',
'Ambattur, Chennai',
'Avadi, Chennai',
'Madipakkam, Chennai',
'Medavakkam, Chennai',
'Pallavaram, Chennai',
'Sholinganallur, Chennai',
'OMR (Old Mahabalipuram Road), Chennai',
'ECR (East Coast Road), Chennai',
'Perungudi, Chennai',
'Thoraipakkam, Chennai',
'Kotturpuram, Chennai',
'Mandaveli, Chennai',
'Triplicane, Chennai',
'Royapuram, Chennai',
'George Town, Chennai',
'Perambur, Chennai',
'Villivakkam, Chennai',
'Kolathur, Chennai',
'Ayanavaram, Chennai',
'Purasawalkam, Chennai',
'Choolaimedu, Chennai',
'Arumbakkam, Chennai',
'Valasaravakkam, Chennai',
'Virugambakkam, Chennai',
'Thiruvanmiyur, Chennai',
'Neelankarai, Chennai',
'Injambakkam, Chennai',
'Pallikaranai, Chennai',
'Kovilambakkam, Chennai',
'Madhavaram, Chennai',
'Red Hills, Chennai',
'Mogappair, Chennai',
'Thirumangalam, Chennai',
'Korattur, Chennai',
'Padi, Chennai',
'Manali, Chennai',
'Ennore, Chennai',
'Tiruvottiyur, Chennai',
'Tondiarpet, Chennai',
'Washermanpet, Chennai',
'Mint Street, Chennai',
'Sowcarpet, Chennai',
'Park Town, Chennai',
'Broadway, Chennai',
'Vepery, Chennai',
'Pattalam, Chennai',
'Pulianthope, Chennai',
'MKB Nagar, Chennai',
'Selaiyur, Chennai',
'Chitlapakkam, Chennai',
'Madambakkam, Chennai',
'Nanmangalam, Chennai',
'Keelkattalai, Chennai',
'Ullagaram, Chennai',
'Puzhuthivakkam, Chennai',
'Adambakkam, Chennai',
'Alandur, Chennai',
'Nanganallur, Chennai',
'St. Thomas Mount, Chennai',
'Meenambakkam, Chennai',
'Anakaputhur, Chennai',
'Pammal, Chennai',
'Kundrathur, Chennai',
'Mudichur, Chennai',
'Perungalathur, Chennai',
'Peerkankaranai, Chennai',
'Vandalur, Chennai',
'Kelambakkam, Chennai',
'Siruseri, Chennai',
'Thaiyur, Chennai',
'Muttukadu, Chennai',
'Kovalam, Chennai',
'Maraimalai Nagar, Chennai',
'Singaperumal Koil, Chennai',
'Sriperumbudur, Chennai',
'Oragadam, Chennai',
'Wallajabad, Chennai',
'Kattankulathur, Chennai',
'Urapakkam, Chennai',
'Guduvancheri, Chennai',
'Karapakkam, Chennai',
'Akkarai, Chennai',
'Panaiyur, Chennai',
'Uthandi, Chennai',
'Semmencherry, Chennai',
'Navalur, Chennai',
'Padur, Chennai',
'Maduravoyal, Chennai',
'Nolambur, Chennai',
'Iyyappanthangal, Chennai',
'Mangadu, Chennai',
'Gerugambakkam, Chennai',
'Ramapuram, Chennai',
'Mugalivakkam, Chennai',
'Manapakkam, Chennai',
'Nesapakkam, Chennai',
'Ekkattuthangal, Chennai',
'Jafferkhanpet, Chennai',
'K K Nagar, Chennai',
'Saligramam, Chennai',
'Anna Nagar West, Chennai',
'Anna Nagar East, Chennai',
'Shenoy Nagar, Chennai',
'Aminjikarai, Chennai',
'Mahalingapuram, Chennai',
'Gopalapuram, Chennai',
'Luz, Chennai',
'Kapaleeswarar Nagar, Chennai',
'Foreshore Estate, Chennai',
'Santhome, Chennai',
'R A Puram, Chennai',
'Boat Club Road, Chennai',
'Poes Garden, Chennai',
'Abhiramapuram, Chennai',
'Vettuvankeni, Chennai',
'Palavakkam, Chennai',
'Kottivakkam, Chennai',
'Periyar Nagar, Chennai',
'Vyasarpadi, Chennai',
'Kodungaiyur, Chennai',
'Erukanchery, Chennai',
'Jamboree Nagar, Chennai',
'Sembium, Chennai',
'GKM Colony, Chennai',
'Agaram, Chennai',
'Chinmaya Nagar, Chennai',
'Nandanam, Chennai',
'CIT Nagar, Chennai',
'Kalaimagal Nagar, Chennai',
'Thirumullaivoyal, Chennai',
'Pattabiram, Chennai',
'Thiruninravur, Chennai',
'Pozhichalur, Chennai',
'Cowl Bazaar, Chennai',
'Hasthinapuram, Chennai',
'Camp Road, Chennai',
'East Tambaram, Chennai',
'West Tambaram, Chennai',
'MEPZ (Madras Export Processing Zone), Chennai',
'Kadapperi, Chennai',
'Rajakilpakkam, Chennai',
'Sembakkam, Chennai',
'Gowrivakkam, Chennai',
'Vengaivasal, Chennai',
'Perumbakkam, Chennai',
'Medavakkam Tank, Chennai',
'Okkiyam, Chennai',
'Madambakkam Tank, Chennai',
'Sithalapakkam, Chennai',
'Ponmar, Chennai',
'Mambakkam, Chennai',
'Ottiyambakkam, Chennai',
'Thalambur, Chennai',
'Karanai, Chennai',
'Kolapakkam, Chennai',
'Vandalur Minjur, Chennai',
'Kolkata, West Bengal',
'Alipore, Kolkata',
'Ballygunge, Kolkata',
'Tollygunge, Kolkata',
'New Alipore, Kolkata',
'Gariahat, Kolkata',
'Salt Lake City, Kolkata',
'Bidhannagar, Kolkata',
'Dum Dum, Kolkata',
'Behala, Kolkata',
'Jadavpur, Kolkata',
'Park Street, Kolkata',
'Esplanade, Kolkata',
'B.B.D. Bagh, Kolkata',
'Bowbazar, Kolkata',
'Burrabazar, Kolkata',
'Shyambazar, Kolkata',
'Maniktala, Kolkata',
'Jorasanko, Kolkata',
'Phoolbagan, Kolkata',
'Kankurgachi, Kolkata',
'Ultadanga, Kolkata',
'Baguiati, Kolkata',
'Rajarhat, Kolkata',
'New Town, Kolkata',
'Garia, Kolkata',
'Patuli, Kolkata',
'Narendrapur, Kolkata',
'Bansdroni, Kolkata',
'Taltala, Kolkata',
'Entally, Kolkata',
'Sealdah, Kolkata',
'College Street, Kolkata',
'Hatibagan, Kolkata',
'Girish Park, Kolkata',
'Sovabazar, Kolkata',
'Kumartuli, Kolkata',
'Sinthe, Kolkata',
'Baranagar, Kolkata',
'Kamarhati, Kolkata',
'Belgharia, Kolkata',
'Agarpara, Kolkata',
'Sodepur, Kolkata',
'North Dumdum, Kolkata',
'South Dumdum, Kolkata',
'Rajpur, Kolkata',
'Madhyamgram, Kolkata',
'Barasat, Kolkata',
'Joka, Kolkata',
'Thakurpukur, Kolkata',
'Metiabruz, Kolkata',
'Garden Reach, Kolkata',
'Kidderpore, Kolkata',
'Chetla, Kolkata',
'Kalighat, Kolkata',
'Bhowanipore, Kolkata',
'Rashbehari, Kolkata',
'Lake Gardens, Kolkata',
'Southern Avenue, Kolkata',
'Dhakuria, Kolkata',
'Golpark, Kolkata',
'Baghajatin, Kolkata',
'Naktala, Kolkata',
'Santoshpur, Kolkata',
'Mukundapur, Kolkata',
'Kasba, Kolkata',
'Bosepukur, Kolkata',
'Haltu, Kolkata',
'Tangra, Kolkata',
'Chinatown, Kolkata',
'Topsia, Kolkata',
'Beliaghata, Kolkata',
'Narkeldanga, Kolkata',
'Beadon Street, Kolkata',
'Amherst Street, Kolkata',
'Raja Bazar, Kolkata',
'Cossipore, Kolkata',
'Chitpur, Kolkata',
'Paikpara, Kolkata',
'Belgachia, Kolkata',
'Tala, Kolkata',
'Jorabagan, Kolkata',
'Posta, Kolkata',
'Strand Road, Kolkata',
'Hare Street, Kolkata',
'Lalbazar, Kolkata',
'Chittaranjan Avenue, Kolkata',
'Central Avenue, Kolkata',
'M G Road, Kolkata',
'Princep Ghat, Kolkata',
'Hastings, Kolkata',
'Watgunge, Kolkata',
'Ekbalpur, Kolkata',
'Mominpur, Kolkata',
'Khidderpore, Kolkata',
'Parnasree, Kolkata',
'Sarsuna, Kolkata',
'Barisha, Kolkata',
'Sakherbazar, Kolkata',
'Paschim Putiary, Kolkata',
'Haridevpur, Kolkata',
'Ramnagar, Kolkata',
'Anandapur, Kolkata',
'East Kolkata Township, Kolkata',
'Chinar Park, Kolkata',
'Keshtopur, Kolkata',
'Teghoria, Kolkata',
'Kaikhali, Kolkata',
'Narayanpur, Kolkata',
'Gopalpur, Kolkata',
'Airport Area, Kolkata',
'Jessore Road, Kolkata',
'Bangur Avenue, Kolkata',
'Lake Town, Kolkata',
'Nagerbazar, Kolkata',
'Motijheel, Kolkata',
'Kestopur, Kolkata',
'Arjunpur, Kolkata',
'Raghunathpur, Kolkata',
'Baguihati, Kolkata',
'Deshbandhu Nagar, Kolkata',
'Krishnapur, Kolkata',
'Sukanta Pally, Kolkata',
'Durganagar, Kolkata',
'Hyderabad, Telangana',
'Banjara Hills, Hyderabad',
'Ram Nagar, Hyderabad',
'Jubilee Hills, Hyderabad',
'Himayatnagar, Hyderabad',
'Secunderabad, Hyderabad',
'Gachibowli, Hyderabad',
'Hitech City, Hyderabad',
'Madhapur, Hyderabad',
'Kukatpally, Hyderabad',
'Ameerpet, Hyderabad',
'Begumpet, Hyderabad',
'Somajiguda, Hyderabad',
'Panjagutta, Hyderabad',
'Khairatabad, Hyderabad',
'Abids, Hyderabad',
'Koti, Hyderabad',
'Nampally, Hyderabad',
'Basheerbagh, Hyderabad',
'Lakdikapul, Hyderabad',
'Mehdipatnam, Hyderabad',
'Tolichowki, Hyderabad',
'Rajendra Nagar, Hyderabad',
'Attapur, Hyderabad',
'Uppal, Hyderabad',
'Dilsukhnagar, Hyderabad',
'Kachiguda, Hyderabad',
'Chikkadpally, Hyderabad',
'Barkatpura, Hyderabad',
'Narayanguda, Hyderabad',
'Habsiguda, Hyderabad',
'Tarnaka, Hyderabad',
'Nacharam, Hyderabad',
'Malkajgiri, Hyderabad',
'Alwal, Hyderabad',
'Bolarum, Hyderabad',
'Sainikpuri, Hyderabad',
'A S Rao Nagar, Hyderabad',
'ECIL, Hyderabad',
'Kapra, Hyderabad',
'Cherlapally, Hyderabad',
'Jeedimetla, Hyderabad',
'Balanagar, Hyderabad',
'Kukatpally Housing Board, Hyderabad',
'Miyapur, Hyderabad',
'Chandanagar, Hyderabad',
'Serilingampally, Hyderabad',
'Hafeezpet, Hyderabad',
'Kondapur, Hyderabad',
'Manikonda, Hyderabad',
'Puppalaguda, Hyderabad',
'Nizampet, Hyderabad',
'Bachupally, Hyderabad',
'Quthbullapur, Hyderabad',
'Chintal, Hyderabad',
'Suraram, Hyderabad',
'Jagadgirigutta, Hyderabad',
'Gajularamaram, Hyderabad',
'Pragathi Nagar, Hyderabad',
'Moosapet, Hyderabad',
'Sanath Nagar, Hyderabad',
'Bharat Nagar, Hyderabad',
'Erragadda, Hyderabad',
'Borabanda, Hyderabad',
'Allwyn Colony, Hyderabad',
'Venkateswara Nagar, Hyderabad',
'KPHB Colony, Hyderabad',
'JNTU Area, Hyderabad',
'Lingampally, Hyderabad',
'Narsingi, Hyderabad',
'Nanakramguda, Hyderabad',
'Financial District, Hyderabad',
'Kokapet, Hyderabad',
'Appa Junction, Hyderabad',
'Hayatnagar, Hyderabad',
'Vanasthalipuram, Hyderabad',
'L B Nagar, Hyderabad',
'Saroornagar, Hyderabad',
'Gaddiannaram, Hyderabad',
'Nagole, Hyderabad',
'Mansoorabad, Hyderabad',
'B N Reddy Nagar, Hyderabad',
'Champapet, Hyderabad',
'Santosh Nagar, Hyderabad',
'Saidabad, Hyderabad',
'Moosarambagh, Hyderabad',
'Malakpet, Hyderabad',
'Amberpet, Hyderabad',
'Bagh Amberpet, Hyderabad',
'New Nallakunta, Hyderabad',
'Ramanthapur, Hyderabad',
'Warasiguda, Hyderabad',
'Padmarao Nagar, Hyderabad',
'Mettuguda, Hyderabad',
'Sitaphalmandi, Hyderabad',
'Chilakalaguda, Hyderabad',
'Bouduppal, Hyderabad',
'Peerzadiguda, Hyderabad',
'Kothapet, Hyderabad',
'Marredpally, Hyderabad',
'East Marredpally, Hyderabad',
'West Marredpally, Hyderabad',
'Bowenpally, Hyderabad',
'New Bowenpally, Hyderabad',
'Old Bowenpally, Hyderabad',
'Hasmathpet, Hyderabad',
'Ferozguda, Hyderabad',
'Balaji Nagar, Hyderabad',
'Lothukunta, Hyderabad',
'Yapral, Hyderabad',
'Kowkur, Hyderabad',
'Turkapally, Hyderabad',
'Gandipet, Hyderabad',
'Bandlaguda, Hyderabad',
'Nagaram, Hyderabad',
'Rampally, Hyderabad',
'Ghatkesar, Hyderabad',
'Pocharam, Hyderabad',
'Adikmet, Hyderabad',
'Vidyanagar, Hyderabad',
'Shivam Road, Hyderabad',
'DD Colony, Hyderabad',
'Baghlingampally, Hyderabad',
'Golnaka, Hyderabad',
'Alkapuri, Hyderabad',
'Jubilee Hills Extension, Hyderabad',
'Film Nagar, Hyderabad',
'Madhura Nagar, Hyderabad',
'Yousufguda, Hyderabad',
'Srinagar Colony, Hyderabad',
'Venkateswara Colony, Hyderabad',
'Kamalapuri Colony, Hyderabad',
'Kavuri Hills, Hyderabad',
'Shaikpet, Hyderabad',
'Durgam Cheruvu, Hyderabad',
'Raidurg, Hyderabad',
'Khajaguda, Hyderabad',
'Gandhamguda, Hyderabad',
'Ashok Nagar, Hyderabad',
'Domalguda, Hyderabad',
'Gunfoundry, Hyderabad',
'Red Hills, Hyderabad',
'Chikkoti Gardens, Hyderabad',
'Vikrampuri, Hyderabad',
'Picket, Hyderabad',
'Trimulgherry, Hyderabad',
'Tirumalgiri, Hyderabad',
'Sikh Village, Hyderabad',
'Diamond Point, Hyderabad',
'Safilguda, Hyderabad',
'Neredmet, Hyderabad',
'Vinayak Nagar, Hyderabad',
'Old Neredmet, Hyderabad',
'Karkhana, Hyderabad',
'Vasavi Nagar, Hyderabad',
'Kakatiya Nagar, Hyderabad',
'Parsigutta, Hyderabad',
'Musheerabad, Hyderabad',
'Zamistanpur, Hyderabad',
'Azamabad, Hyderabad',
'Puranapool, Hyderabad',
'Falaknuma, Hyderabad',
'Chandrayangutta, Hyderabad',
'Barkas, Hyderabad',
'Uppuguda, Hyderabad',
'Jangammet, Hyderabad',
'Fateh Darwaza, Hyderabad',
'Shah Ali Banda, Hyderabad',
'Vattepally, Hyderabad',
'Moghalpura, Hyderabad',
'Shalibanda, Hyderabad',
'Hussaini Alam, Hyderabad',
'Ghansi Bazaar, Hyderabad',
'Goshamahal, Hyderabad',
'Afzal Gunj, Hyderabad',
'Osman Gunj, Hyderabad',
'Chaderghat, Hyderabad',
'Moti Nagar, Hyderabad',
'Vengal Rao Nagar, Hyderabad',
'Greenlands, Hyderabad',
'Prakash Nagar, Hyderabad',
'Ameerpet Extension, Hyderabad',
'S R Nagar, Hyderabad',
'Sanjeeva Reddy Nagar, Hyderabad',
'Czech Colony, Hyderabad',
'AG Colony, Hyderabad',
'Venkata Ramana Colony, Hyderabad',
'Lanco Hills, Hyderabad',
'Don Bosco Nagar, Hyderabad',
'Anandbagh, Hyderabad',
'Safilguda Extension, Hyderabad',
'Sainathpuram, Hyderabad',
'Dr A S Rao Nagar, Hyderabad',
'Old Safilguda, Hyderabad',
'Dammaiguda, Hyderabad',
'Saket, Hyderabad',
'Jawahar Nagar, Hyderabad',
'Nagaram Extension, Hyderabad',
'Gaddi Annaram, Hyderabad',
'Badangpet, Hyderabad',
'Balapur, Hyderabad',
'Meerpet, Hyderabad',
'Kurmaguda, Hyderabad',
'Mailardevpally, Hyderabad',
'Pahadi Shareef, Hyderabad',
'Hydershakote, Hyderabad',
'Ibrahim Bagh, Hyderabad',
'Golkonda, Hyderabad',
'Langar Houz, Hyderabad',
'Asif Nagar, Hyderabad',
'Mehdipatnam Extension, Hyderabad',
'Suncity, Hyderabad',
'Bandlaguda Jagir, Hyderabad',
'Premavathipet, Hyderabad',
'Nawab Saheb Kunta, Hyderabad',
'Tadbund, Hyderabad',
'Methodist Colony, Hyderabad',
'Park View Enclave, Hyderabad',
'Venkatapuram, Hyderabad',
'Lothkunta, Hyderabad',
'Bhagyanagar, Hyderabad',
'Bhawani Nagar, Hyderabad',
'Old Alwal, Hyderabad',
'Macha Bolarum, Hyderabad',
'Risala Bazaar, Hyderabad',
'Ahmedabad, Gujarat',
'Ambawadi, Ahmedabad',
'Bodakdev, Ahmedabad',
'Bopal, Ahmedabad',
'C.G. Road, Ahmedabad',
'Ellisbridge, Ahmedabad',
'Ghatlodia, Ahmedabad',
'Gota, Ahmedabad',
'Gurukul, Ahmedabad',
'Maninagar, Ahmedabad',
'Memnagar, Ahmedabad',
'Naranpura, Ahmedabad',
'Naroda, Ahmedabad',
'Navrangpura, Ahmedabad',
'Paldi, Ahmedabad',
'Prahlad Nagar, Ahmedabad',
'Sabarmati, Ahmedabad',
'Satellite, Ahmedabad',
'Thaltej, Ahmedabad',
'Vastrapur, Ahmedabad',
'Ashram Road, Ahmedabad',
'Chandkheda, Ahmedabad',
'Drive-In Road, Ahmedabad',
'Juhapura, Ahmedabad',
'Kalupur, Ahmedabad',
'Khadia, Ahmedabad',
'Shahibaug, Ahmedabad',
'Vasna, Ahmedabad',
'Vejalpur, Ahmedabad',
'Bapunagar, Ahmedabad',
'Jamalpur, Ahmedabad',
'Raipur, Ahmedabad',
'Saraspur, Ahmedabad',
'Shahpur, Ahmedabad',
'Amraiwadi, Ahmedabad',
'Asarwa, Ahmedabad',
'Behrampura, Ahmedabad',
'Danilimda, Ahmedabad',
'Dariapur, Ahmedabad',
'Gomtipur, Ahmedabad',
'Kankaria, Ahmedabad',
'Khokhra, Ahmedabad',
'Odhav, Ahmedabad',
'Rakhial, Ahmedabad',
'Vatva, Ahmedabad',
'Isanpur, Ahmedabad',
'Ghodasar, Ahmedabad',
'Nikol, Ahmedabad',
'Ranip, Ahmedabad',
'Meghaninagar, Ahmedabad',
'Saijpur Bogha, Ahmedabad',
'Thakkarbapa Nagar, Ahmedabad',
'Hansol, Ahmedabad',
'Motera, Ahmedabad',
'New Ranip, Ahmedabad',
'Chandlodia, Ahmedabad',
'Nava Vadaj, Ahmedabad',
'Sardarnagar, Ahmedabad',
'Girdharnagar, Ahmedabad',
'Madhupura, Ahmedabad',
'Dudheshwar, Ahmedabad',
'Shah-e-Alam, Ahmedabad',
'Jivraj Park, Ahmedabad',
'Shyamal Cross Road, Ahmedabad',
'South Bopal, Ahmedabad',
'Shela, Ahmedabad',
'Sola, Ahmedabad',
'Science City, Ahmedabad',
'S.G. Highway, Ahmedabad',
'Makarba, Ahmedabad',
'Nehrunagar, Ahmedabad',
'Sindhu Bhavan Road, Ahmedabad',
'Anandnagar, Ahmedabad',
'Usmanpura, Ahmedabad',
'Fatehpura, Ahmedabad',
'Bhuyangdev, Ahmedabad',
'Nava Naroda, Ahmedabad',
'Krishna Nagar, Ahmedabad',
'Ramdev Nagar, Ahmedabad',
'Sanand, Ahmedabad',
'Bavla, Ahmedabad',
'Kubernagar, Ahmedabad',
'Giriraj Society, Ahmedabad',
'Lambha, Ahmedabad',
'Narol, Ahmedabad',
'Vinzol, Ahmedabad',
'Hathijan, Ahmedabad',
'Bareja, Ahmedabad',
'Kamod, Ahmedabad',
'Geratpur, Ahmedabad',
'Aslali, Ahmedabad',
'Bakrol, Ahmedabad',
'Jashodanagar, Ahmedabad',
'CTM, Ahmedabad',
'Ramol, Ahmedabad',
'Vastral, Ahmedabad',
'Hathikhali, Ahmedabad',
'Singarva, Ahmedabad',
'Kathwada, Ahmedabad',
'Bhadaj, Ahmedabad',
'Kali, Ahmedabad',
'Tragad, Ahmedabad',
'Lapkaman, Ahmedabad',
'Kolat, Ahmedabad',
'Rancharda, Ahmedabad',
'Vaishnodevi Circle, Ahmedabad',
'Jagatpur, Ahmedabad',
'Chenpur, Ahmedabad',
'Shilaj, Ahmedabad',
'Ambli, Ahmedabad',
'Hebatpur, Ahmedabad',
'Bhadra, Ahmedabad',
'Gheekanta, Ahmedabad',
'Lal Darwaza, Ahmedabad',
'Astodia, Ahmedabad',
'Pankore Naka, Ahmedabad',
'Tankshal, Ahmedabad',
'Mirzapur, Ahmedabad',
'Revdi Bazar, Ahmedabad',
'Dhalgarwad, Ahmedabad',
'Ratanpole, Ahmedabad',
'Manek Chowk, Ahmedabad',
'Teen Darwaza, Ahmedabad',
'Gandhi Road, Ahmedabad',
'Relief Road, Ahmedabad',
'Khanpur, Ahmedabad',
'Raikhad, Ahmedabad',
'Behrampura Extension, Ahmedabad',
'Sukhram Nagar, Ahmedabad',
'Chamanpura, Ahmedabad',
'Fatehwadi, Ahmedabad',
'Maktampura, Ahmedabad',
'Chandola, Ahmedabad',
'Bhulabhai Park, Ahmedabad',
'Keshav Nagar, Ahmedabad',
'Subhash Bridge, Ahmedabad',
'Nirnaynagar, Ahmedabad',
'Vadaj, Ahmedabad',
'Oganaj, Ahmedabad',
'Gulbai Tekra, Ahmedabad',
'Kankaria Lake, Ahmedabad',
'Law Garden, Ahmedabad',
'Parimal Garden, Ahmedabad',
'Riverfront, Ahmedabad',
'Vastrapur Lake, Ahmedabad',
'Sabarmati Ashram, Ahmedabad',
'Kankaria Tank, Ahmedabad',
'Balvatika, Ahmedabad',
'Kamala Nehru Park, Ahmedabad',
'Lal Darwaja, Ahmedabad',
'Bhadra Fort, Ahmedabad',
'Jhulta Minar, Ahmedabad',
'Siddi Saiyed Mosque, Ahmedabad',
'Jama Masjid, Ahmedabad',
'Hathee Singh Jain Temple, Ahmedabad',
'Swaminarayan Temple, Ahmedabad',
'Sarkhej Roza, Ahmedabad',
'Sanskar Kendra, Ahmedabad',
'Calico Textile Museum, Ahmedabad',
'Shreyas Folk Museum, Ahmedabad',
'Gujarat Science City, Ahmedabad',
'Kamla Nehru Zoo, Ahmedabad',
'Sundarvan Nature Discovery Centre, Ahmedabad',
'Parimal Crossing, Ahmedabad',
'Gurudwara Gobind Dham, Ahmedabad',
'ISKCON Temple, Ahmedabad',
'Jami Masjid, Ahmedabad',
'Rani no Hajiro, Ahmedabad',
'Sidi Bashir Mosque, Ahmedabad',
'Nagina Wadi, Ahmedabad',
'Kankaria Zoo, Ahmedabad',
'Vastrapur Amphitheatre, Ahmedabad',
'IIM Ahmedabad, Ahmedabad',
'CEPT University, Ahmedabad',
'NID Campus, Ahmedabad',
'Gujarat University, Ahmedabad',
'LD College of Engineering, Ahmedabad',
'PRL Campus, Ahmedabad',
'Space Application Centre, Ahmedabad',
'Vikram Sarabhai Community Science Centre, Ahmedabad',
'Lalbhai Dalpatbhai Museum, Ahmedabad',
'NC Mehta Gallery, Ahmedabad',
'Kasturbhai Lalbhai Museum, Ahmedabad',
'Darpana Academy of Performing Arts, Ahmedabad',
'Ahmedabad Haat, Ahmedabad',
'Manek Burman, Ahmedabad',
'Teen Darwaza, Ahmedabad',
'Fernandes Bridge, Ahmedabad',
'Rani Sipri Mosque, Ahmedabad',
'Dastur Khan Mosque, Ahmedabad',
'Bai Harir Stepwell, Ahmedabad',
'Mata Bhavani’s Stepwell, Ahmedabad',
'Amritvarshini Vav, Ahmedabad',
'Dada Harir Stepwell, Ahmedabad',
'Shahi Baug, Ahmedabad',
'Kochrab Ashram, Ahmedabad',
'Gandhi Smarak Sangrahalaya, Ahmedabad',
'Tagore Hall, Ahmedabad',
'Natarani Amphitheatre, Ahmedabad',
'Dandi Bridge, Ahmedabad',
'Nehru Bridge, Ahmedabad',
'Ellis Bridge, Ahmedabad',
'Gandhi Bridge, Ahmedabad',
'Subhash Bridge, Ahmedabad',
'Sardar Patel Stadium, Ahmedabad',
'Motera Stadium, Ahmedabad',
'Naroda Industrial Area, Ahmedabad',
'Vatva Industrial Area, Ahmedabad',
'Odhav Industrial Area, Ahmedabad',
'Changodar Industrial Area, Ahmedabad',
'Sanand Industrial Area, Ahmedabad',
'Kathwada GIDC, Ahmedabad',
'Bavla GIDC, Ahmedabad',
'Chhatral GIDC, Ahmedabad',
'Kalol GIDC, Ahmedabad',
'Kadi GIDC, Ahmedabad',
'Mehsana GIDC, Ahmedabad',
'Gandhinagar GIDC, Ahmedabad',
'Dahegam GIDC, Ahmedabad',
'Vithalapur GIDC, Ahmedabad',
'Santej GIDC, Ahmedabad',
'Moraiya GIDC, Ahmedabad',
'Kerala GIDC, Ahmedabad',
'Dholka GIDC, Ahmedabad',
'Viramgam GIDC, Ahmedabad',
'Mandal GIDC, Ahmedabad',
'Zak GIDC, Ahmedabad',
'Dehgam GIDC, Ahmedabad',
'Rakanpur, Ahmedabad',
'Santej, Ahmedabad',
'Khatraj, Ahmedabad',
'Karoli, Ahmedabad',
'Rupal, Ahmedabad',
'Saij, Ahmedabad',
'Kanbha, Ahmedabad',
'Pune, Maharashtra',
'Koregaon Park, Pune',
'Kalyani Nagar, Pune',
'Viman Nagar, Pune',
'Hadapsar, Pune',
'Baner, Pune',
'Aundh, Pune',
'Kothrud, Pune',
'Shivaji Nagar, Pune',
'Deccan Gymkhana, Pune',
'Camp, Pune',
'Hinjewadi, Pune',
'Wakad, Pune',
'Pimpri, Pune',
'Chinchwad, Pune',
'Magarpatta, Pune',
'Kharadi, Pune',
'Yerwada, Pune',
'Swargate, Pune',
'Katraj, Pune',
'Warje, Pune',
'Bavdhan, Pune',
'Pashan, Pune',
'Sus, Pune',
'Nanded, Pune',
'Sinhagad Road, Pune',
'Dhayari, Pune',
'Bhawani Peth, Pune',
'Bibwewadi, Pune',
'Kondhwa, Pune',
'Wanowrie, Pune',
'Fatima Nagar, Pune',
'Mundhwa, Pune',
'Lohegaon, Pune',
'Wagholi, Pune',
'Vishrantwadi, Pune',
'Dhanori, Pune',
'Erandwane, Pune',
'Karve Nagar, Pune',
'Parvati, Pune',
'Sadashiv Peth, Pune',
'Narayan Peth, Pune',
'Shaniwar Peth, Pune',
'Budhwar Peth, Pune',
'Rasta Peth, Pune',
'Ghorpadi, Pune',
'Model Colony, Pune',
'Senapati Bapat Road, Pune',
'Fergusson College Road, Pune',
'JM Road, Pune',
'FC Road, Pune',
'Balewadi, Pune',
'Pimple Saudagar, Pune',
'Pimple Gurav, Pune',
'Pimple Nilakh, Pune',
'Sangvi, Pune',
'Thergaon, Pune',
'Ravet, Pune',
'Tathawade, Pune',
'Akurdi, Pune',
'Nigdi, Pune',
'Dapodi, Pune',
'Khadki, Pune',
'Bopodi, Pune',
'Kasba Peth, Pune',
'Somwar Peth, Pune',
'Mangalwar Peth, Pune',
'Guruwar Peth, Pune',
'Shukrawar Peth, Pune',
'Raviwar Peth, Pune',
'Nana Peth, Pune',
'Bhosari, Pune',
'Chakan, Pune',
'Talawade, Pune',
'Moshi, Pune',
'Chikhali, Pune',
'Dehu Road, Pune',
'Alandi, Pune',
'Vadgaon, Pune',
'Ambegaon, Pune',
'Undri, Pune',
'Pisoli, Pune',
'Lulla Nagar, Pune',
'Mohammadwadi, Pune',
'NIBM Road, Pune',
'Salisbury Park, Pune',
'Market Yard, Pune',
'Gultekdi, Pune',
'Maharshi Nagar, Pune',
'Mukund Nagar, Pune',
'Satara Road, Pune',
'Padmavati, Pune',
'Sahakar Nagar, Pune',
'Tukaram Nagar, Pune',
'Talegaon, Pune',
'Lonikand, Pune',
'Uruli Kanchan, Pune',
'Phursungi, Pune',
'Manjri, Pune',
'Keshav Nagar, Pune',
'Tingre Nagar, Pune',
'Sancheti Nagar, Pune',
'Shivane, Pune',
'Uttam Nagar, Pune',
'Narhe, Pune',
'Dhankawadi, Pune',
'Khadakwasla, Pune',
'Hingne Khurd, Pune',
'Kirkatwadi, Pune',
'Vadgaon Budruk, Pune',
'Vadgaon Sheri, Pune',
'Mundhwa Road, Pune',
'Kondhwa Budruk, Pune',
'Kondhwa Khurd, Pune',
'Balaji Nagar, Pune',
'Anand Nagar, Pune',
'Manik Baug, Pune',
'Hingane Mala, Pune',
'Sasane Nagar, Pune',
'Ramtekdi, Pune',
'Kalyani Nagar Annexe, Pune',
'Koregaon Park Annexe, Pune',
'Sopan Baug, Pune',
'Boat Club Road, Pune',
'Bund Garden, Pune',
'Sangamvadi, Pune',
'Dhole Patil Road, Pune',
'Kalyani Nagar Extension, Pune',
'Shastri Nagar, Pune',
'Amanora Park, Pune',
'Hadapsar Industrial Area, Pune',
'Fursungi IT Park, Pune',
'SP Infocity, Pune',
'EON IT Park, Pune',
'Kharadi IT Park, Pune',
'Hinjewadi IT Park, Pune',
'Magarpatta IT City, Pune',
'Kothrud Paud Road, Pune',
'Law College Road, Pune',
'Prabhat Road, Pune',
'Bhandarkar Road, Pune',
'Apte Road, Pune',
'Kothrud Depot, Pune',
'Bhusari Colony, Pune',
'Ideal Colony, Pune',
'Mayur Colony, Pune',
'Rambaug Colony, Pune',
'Paud Road, Pune',
'Bavdhan Khurd, Pune',
'Bavdhan Budruk, Pune',
'Pashan Road, Pune',
'Sutarwadi, Pune',
'Someshwarwadi, Pune',
'Pashan-Sus Road, Pune',
'Baner Road, Pune',
'Balewadi High Street, Pune',
'Baner-Pashan Link Road, Pune',
'Aundh Annexe, Pune',
'New Sangvi, Pune',
'Old Sangvi, Pune',
'Pimple Gurav Extension, Pune',
'Pimple Saudagar Extension, Pune',
'Wakad Extension, Pune',
'Tathawade Extension, Pune',
'Punawale, Pune',
'Marunji, Pune',
'Mamurdi, Pune',
'Gahunje, Pune',
'Mhalunge, Pune',
'Nere, Pune',
'Somathane, Pune',
'Kiwale, Pune',
'Jambe, Pune',
'Hinjawadi Phase 1, Pune',
'Hinjawadi Phase 2, Pune',
'Hinjawadi Phase 3, Pune',
'Dattawadi, Pune',
'Navi Peth, Pune',
'Laxmi Road, Pune',
'Bajirao Road, Pune',
'Tilak Road, Pune',
'Kumthekar Road, Pune',
'Appa Balwant Chowk, Pune',
'Kondhwa Road, Pune',
'Gangadham, Pune',
'Shankar Sheth Road, Pune',
'Solapur Road, Pune',
'Nagar Road, Pune',
'Yerwada Bazaar, Pune',
'Khadki Bazaar, Pune',
'Aundh Road, Pune',
'Ganeshkhind Road, Pune',
'University Road, Pune',
'Pune Station Area, Pune',
'Bund Garden Road, Pune',
'Wellesley Road, Pune',
'East Street, Pune',
'Moledina Road, Pune',
'MG Road, Pune',
'North Main Road, Pune',
'Koregaon Park North, Pune',
'Koregaon Park South, Pune',
'Pune Cantonment, Pune',
'Wanorie, Pune',
'Gokul Nagar, Pune',
'Saswad Road, Pune',
'Pandurang Colony, Pune',
'Shivraj Nagar, Pune',
'Samarth Nagar, Pune',
'Siddhant Nagar, Pune',
'Vishal Nagar, Pune',
'Jagtap Dairy, Pune',
'Rahatani, Pune',
'Chintamani Nagar, Pune',
'Shree Nagar, Pune',
'Dighi, Pune',
'Bhosari Industrial Area, Pune',
'MIDC Bhosari, Pune',
'Pimpri Industrial Area, Pune',
'Chinchwad Industrial Area, Pune',
'Dhanraj Park, Pune',
'Wakadewadi, Pune',
'Shivaji Housing Society, Pune',
'Revenue Colony, Pune',
'Gokhale Nagar, Pune',
'Range Hills, Pune',
'Ashok Nagar, Pune',
'Bopkhel, Pune',
'Charholi, Pune',
'Alandi Road, Pune',
'Wadgaon Sheri, Pune',
'Sainath Nagar, Pune',
'Chandkhed, Pune',
'Mauje, Pune',
'Kaspate Wasti, Pune',
'Bhugaon, Pune',
'Lavale, Pune',
'Pirangut, Pune',
'Mulshi, Pune',
'Kesnand, Pune',
'Bakori, Pune',
'Uruli Devachi, Pune',
'Yewalewadi, Pune',
'Kondhawe Dhawade, Pune',
'Kopa, Pune',
'Khed Shivapur, Pune',
'Sanaswadi, Pune',
'Shikrapur, Pune',
'Ranjangaon, Pune',
'Koregaon Bhima, Pune',
'Perne, Pune',
'Wadebolai, Pune',
'Pimplegaon, Pune',
'Dudulgaon, Pune',
'Chakan Industrial Area, Pune',
'Talegaon Industrial Area, Pune',
'MIDC Ranjangaon, Pune',
'MIDC Chakan, Pune',
'MIDC Hinjawadi, Pune',
'MIDC Talawade, Pune',
'Shivapur, Pune',
'Jejuri, Pune',
'Saswad, Pune',
'Purandar, Pune',
'Daund, Pune',
'Baramati, Pune',
'Velu, Pune',
'Nira, Pune',
'Walhe, Pune',
'Kanhe, Pune',
'Ambi, Pune',
'Varale, Pune',
'Kamshet, Pune',
'Wadgaon Maval, Pune',
'Khadkale, Pune',
'Talegaon Dabhade, Pune',
'Lonavala, Pune',
'Khandala, Pune',
'Kusgaon, Pune',
'Maval, Pune',
'Karunj, Pune',
'Pawna Nagar, Pune',
'Shilimb, Pune',
'Moshi Pradhikaran, Pune',
'Chakan MIDC, Pune',
'Bhawarapur, Pune',
'Khadki Cantonment, Pune',
'Pune University Area, Pune',
'MIT College Area, Pune',
'COEP Area, Pune',
'Symbiosis Viman Nagar, Pune',
'Symbiosis Lavale, Pune',
'Vishwakarma Institute Area, Pune',
'DY Patil Lohegaon, Pune',
'DY Patil Pimpri, Pune',
'Balaji Vishwa, Pune',
'Phoenix Mall Area, Pune',
'Seasons Mall Area, Pune',
'Amanora Mall Area, Pune',
'Inox Mall Area, Pune',
'Westend Mall, Pune',
'Kumar Pacific Mall, Pune',
'City Pride Kothrud, Pune',
'E-Square, Pune',
'Fun Time Multiplex, Pune',
'PVR Koregaon Park, Pune',
'Cinepolis VIP, Pune',
'Balewadi Stadium Area, Pune',
'Shree Shiv Chhatrapati Sports Complex, Pune',
'Aundh ITI, Pune',
'Pashan Lake, Pune',
'Baner Hill, Pune',
'Parvati Hill, Pune',
'Taljai Hills, Pune',
'Vetal Tekdi, Pune',
'Hanuman Tekdi, Pune',
'Chaturshringi Temple Area, Pune',
'Pataleshwar Caves Area, Pune',
'Shaniwar Wada Area, Pune',
'Vishrambaug Wada Area, Pune',
'Kelkar Museum Area, Pune',
'Aga Khan Palace Area, Pune',
'Katraj Lake, Pune',
'Peshwe Park, Pune',
'Saras Baug, Pune',
'Kamala Nehru Park, Pune',
'Sambhaji Park, Pune',
'Chittaranjan Vatika, Pune',
'Empress Garden, Pune',
'Okayama Friendship Garden, Pune',
'Bund Garden Park, Pune',
'Osho Garden, Pune',
'Koregaon Park Garden, Pune',
'Race Course, Pune',
'Pune Golf Course, Pune',
'Poona Club, Pune',
'Royal Connaught Boat Club, Pune',
'Deccan College Area, Pune',
'Savitribai Phule University, Pune',
'Film and Television Institute, Pune',
'National Defence Academy, Pune',
'Khadakwasla Dam, Pune',
'Mulshi Dam, Pune',
'Panshet Dam, Pune',
'Varasgaon Dam, Pune',
'Pavana Dam, Pune',
'Bhawani Peth Extension, Pune',
'Yerwada Extension, Pune',
'Kondhwa Extension, Pune',
'Hadapsar Extension, Pune',
'Wakad Annexe, Pune',
'Baner Annexe, Pune',
'Kothrud Annexe, Pune',
'Pimple Nilakh Annexe, Pune',
'Viman Nagar Annexe, Pune',
'Kalyani Nagar Annexe, Pune',
'Magarpatta Annexe, Pune',
'Kharadi Annexe, Pune',
'Hinjewadi Annexe, Pune',
'Pimpri Annexe, Pune',
'Chinchwad Annexe, Pune',
'Aundh Annexe, Pune',
'Katraj Annexe, Pune',
'Warje Annexe, Pune',
'Bibwewadi Annexe, Pune',
'Sahakar Nagar Annexe, Pune',
'Sadashiv Peth Annexe, Pune',
'Shivaji Nagar Annexe, Pune',
'Deccan Gymkhana Annexe, Pune',
'Camp Annexe, Pune',
'Swargate Annexe, Pune',
'Parvati Annexe, Pune',
'Erandwane Annexe, Pune',
'Karve Nagar Annexe, Pune',
'Khadki Annexe, Pune',
'Bopodi Annexe, Pune',
'Dapodi Annexe, Pune',
'Pashan Annexe, Pune',
'Bavdhan Annexe, Pune',
'Sus Annexe, Pune',
'Nanded Annexe, Pune',
'Dhankawadi Annexe, Pune',
'Ambegaon Annexe, Pune',
'Undri Annexe, Pune',
'Wanorie Annexe, Pune',
'Fatima Nagar Annexe, Pune',
'Mundhwa Annexe, Pune',
'Lohegaon Annexe, Pune',
'Wagholi Annexe, Pune',
'Vishrantwadi Annexe, Pune',
'Dhanori Annexe, Pune',
'Tingre Nagar Annexe, Pune',
'Keshav Nagar Annexe, Pune',
'Manjri Annexe, Pune',
'Phursungi Annexe, Pune',
'Sasane Nagar Annexe, Pune',
'Ramtekdi Annexe, Pune',
'Sopan Baug Annexe, Pune',
'Sangamvadi Annexe, Pune',
'Shastri Nagar Annexe, Pune',
'Sancheti Nagar Annexe, Pune',
'Shivane Annexe, Pune',
'Uttam Nagar Annexe, Pune',
'Narhe Annexe, Pune',
'Khadakwasla Annexe, Pune',
'Hingne Khurd Annexe, Pune',
'Kirkatwadi Annexe, Pune',
'Vadgaon Budruk Annexe, Pune',
'Vadgaon Sheri Annexe, Pune',
'Kondhwa Budruk Annexe, Pune',
'Kondhwa Khurd Annexe, Pune',
'Balaji Nagar Annexe, Pune',
'Anand Nagar Annexe, Pune',
'Manik Baug Annexe, Pune',
'Hingane Mala Annexe, Pune',
'Pune Airport Area, Pune',
'Pune Railway Station Area, Pune',
'Shivaji Market, Pune',
'Laxmi Road Market, Pune',
'Tulsi Baug, Pune',
'Mandai, Pune',
'Dagdusheth Halwai Temple Area, Pune',
'Vishram Baug Wada, Pune',
'Bhagat Singh Nagar, Pune',
'Navi Sadashiv Peth, Pune',
'Lokmanya Nagar, Pune',
'Sneh Nagar, Pune',
'Navi Kasba, Pune',
'Bhawani Peth Market, Pune',
'Ganesh Peth, Pune',
'Siddharth Nagar, Pune',
'Ram Nagar, Pune',
'Shankar Nagar, Pune',
'Vishnu Nagar, Pune',
'Adarsh Nagar, Pune',
'Sunder Nagar, Pune',
'Sai Nagar, Pune',
'Shanti Nagar, Pune',
'Jai Bhawani Nagar, Pune',
'Shiv Shakti Nagar, Pune',
'Samarth Colony, Pune',
'Siddhi Vinayak Nagar, Pune',
'Ganesh Nagar, Pune',
'Ambedkar Nagar, Pune',
'Indira Nagar, Pune',
'Shiv Colony, Pune',
'Krantiveer Nagar, Pune',
'Vivek Nagar, Pune',
'Surya Nagar, Pune',
'Jyoti Nagar, Pune',
'Shree Ram Nagar, Pune',
'Mahatma Phule Nagar, Pune',
'Pandav Nagar, Pune',
'Sanjay Nagar, Pune',
'Savitri Nagar, Pune',
'Tukaram Nagar, Pune',
'Vidya Nagar, Pune',
'Vikas Nagar, Pune',
'Yashwant Nagar, Pune',
'Bhawani Nagar, Pune',
'Chaitanya Nagar, Pune',
'Dattanagar, Pune',
'Guru Nanak Nagar, Pune',
'Jijamata Nagar, Pune',
'Kaveri Nagar, Pune',
'Laxmi Nagar, Pune',
'Mahavir Nagar, Pune',
'Maratha Nagar, Pune',
'Navjeevan Nagar, Pune',
'Netaji Nagar, Pune',
'Omkar Nagar, Pune',
'Parshuram Nagar, Pune',
'Rajiv Gandhi Nagar, Pune',
'Ramnagar, Pune',
'Sahyadri Nagar, Pune',
'Sambhaji Nagar, Pune',
'Sanjivani Nagar, Pune',
'Saraswati Nagar, Pune',
'Shivneri Nagar, Pune',
'Shri Krishna Nagar, Pune',
'Subhash Nagar, Pune',
'Swaroop Nagar, Pune',
'Usha Nagar, Pune',
'Vijay Nagar, Pune',
'Vinoba Nagar, Pune',
'Vithal Nagar, Pune',
'Yashoda Nagar, Pune',
'Bhawani Peth Annexe, Pune',
'Yerwada Annexe, Pune',
'Kondhwa Annexe, Pune',
'Hadapsar Annexe, Pune',
'Wakad Annexe, Pune',
'Baner Annexe, Pune',
'Kothrud Annexe, Pune',
'Pimple Nilakh Annexe, Pune',
'Viman Nagar Annexe, Pune',
'Kalyani Nagar Annexe, Pune',
'Magarpatta Annexe, Pune',
'Kharadi Annexe, Pune',
'Hinjewadi Annexe, Pune',
'Pimpri Annexe, Pune',
'Chinchwad Annexe, Pune',
'Aundh Annexe, Pune',
'Katraj Annexe, Pune',
'Warje Annexe, Pune',
'Bibwewadi Annexe, Pune',
'Sahakar Nagar Annexe, Pune',
'Sadashiv Peth Annexe, Pune',
'Shivaji Nagar Annexe, Pune',
'Deccan Gymkhana Annexe, Pune',
'Camp Annexe, Pune',
'Swargate Annexe, Pune',
'Parvati Annexe, Pune',
'Erandwane Annexe, Pune',
'Karve Nagar Annexe, Pune',
'Khadki Annexe, Pune',
'Bopodi Annexe, Pune',
'Dapodi Annexe, Pune',
'Pashan Annexe, Pune',
'Bavdhan Annexe, Pune',
'Sus Annexe, Pune',
'Nanded Annexe, Pune',
'Dhankawadi Annexe, Pune',
'Ambegaon Annexe, Pune',
'Undri Annexe, Pune',
'Wanorie Annexe, Pune',
'Fatima Nagar Annexe, Pune',
'Mundhwa Annexe, Pune',
'Lohegaon Annexe, Pune',
'Wagholi Annexe, Pune',
'Vishrantwadi Annexe, Pune',
'Dhanori Annexe, Pune',
'Tingre Nagar Annexe, Pune',
'Keshav Nagar Annexe, Pune',
'Manjri Annexe, Pune',
'Phursungi Annexe, Pune',
'Sasane Nagar Annexe, Pune',
'Ramtekdi Annexe, Pune',
'Sopan Baug Annexe, Pune',
'Sangamvadi Annexe, Pune',
'Shastri Nagar Annexe, Pune',
'Sancheti Nagar Annexe, Pune',
'Shivane Annexe, Pune',
'Uttam Nagar Annexe, Pune',
'Narhe Annexe, Pune',
'Khadakwasla Annexe, Pune',
'Hingne Khurd Annexe, Pune',
'Kirkatwadi Annexe, Pune',
'Vadgaon Budruk Annexe, Pune',
'Vadgaon Sheri Annexe, Pune',
'Kondhwa Budruk Annexe, Pune',
'Kondhwa Khurd Annexe, Pune',
'Balaji Nagar Annexe, Pune',
'Anand Nagar Annexe, Pune',
'Manik Baug Annexe, Pune',
'Hingane Mala Annexe, Pune',
'Pune Airport Area, Pune',
'Pune Railway Station Area, Pune',
'Shivaji Market, Pune',
'Laxmi Road Market, Pune',
'Tulsi Baug, Pune',
'Mandai, Pune',
'Dagdusheth Halwai Temple Area, Pune',
'Vishram Baug Wada, Pune',
'Bhagat Singh Nagar, Pune',
'Navi Sadashiv Peth, Pune',
'Lokmanya Nagar, Pune',
'Sneh Nagar, Pune',
'Navi Kasba, Pune',
'Bhawani Peth Market, Pune',
'Ganesh Peth, Pune',
'Siddharth Nagar, Pune',
'Ram Nagar, Pune',
'Shankar Nagar, Pune',
'Vishnu Nagar, Pune',
'Adarsh Nagar, Pune',
'Sunder Nagar, Pune',
'Sai Nagar, Pune',
'Shanti Nagar, Pune',
'Jai Bhawani Nagar, Pune',
'Shiv Shakti Nagar, Pune',
'Samarth Colony, Pune',
'Siddhi Vinayak Nagar, Pune',
'Ganesh Nagar, Pune',
'Ambedkar Nagar, Pune',
'Indira Nagar, Pune',
'Shiv Colony, Pune',
'Krantiveer Nagar, Pune',
'Vivek Nagar, Pune',
'Surya Nagar, Pune',
'Jyoti Nagar, Pune',
'Shree Ram Nagar, Pune',
'Mahatma Phule Nagar, Pune',
'Pandav Nagar, Pune',
'Sanjay Nagar, Pune',
'Savitri Nagar, Pune',
'Tukaram Nagar, Pune',
'Vidya Nagar, Pune',
'Vikas Nagar, Pune',
'Yashwant Nagar, Pune',
'Bhawani Nagar, Pune',
'Chaitanya Nagar, Pune',
'Dattanagar, Pune',
'Guru Nanak Nagar, Pune',
'Jijamata Nagar, Pune',
'Kaveri Nagar, Pune',
'Laxmi Nagar, Pune',
'Mahavir Nagar, Pune',
'Maratha Nagar, Pune',
'Navjeevan Nagar, Pune',
'Netaji Nagar, Pune',
'Omkar Nagar, Pune',
'Parshuram Nagar, Pune',
'Rajiv Gandhi Nagar, Pune',
'Ramnagar, Pune',
'Sahyadri Nagar, Pune',
'Sambhaji Nagar, Pune',
'Sanjivani Nagar, Pune',
'Saraswati Nagar, Pune',
'Shivneri Nagar, Pune',
'Shri Krishna Nagar, Pune',
'Subhash Nagar, Pune',
'Swaroop Nagar, Pune',
'Usha Nagar, Pune',
'Vijay Nagar, Pune',
'Vinoba Nagar, Pune',
'Vithal Nagar, Pune',
'Yashoda Nagar, Pune',
'Balewadi Phata, Pune',
'Dange Chowk, Pune',
'Chinchwad Gaon, Pune',
'Pimpri Gaon, Pune',
'Kalewadi, Pune',
'Kasarwadi, Pune',
'Phugewadi, Pune',
'Pune Nashik Road, Pune',
'Mumbai Pune Highway, Pune',
'Old Mumbai Pune Highway, Pune',
'Baner Mahalunge Road, Pune',
'Wakad Hinjawadi Road, Pune',
'Aundh Ravet Road, Pune',
'Kothrud Karve Road, Pune',
'Pashan Baner Link Road, Pune',
'Pune Solapur Road, Pune',
'Pune Ahmednagar Road, Pune',
'Pune Satara Road, Pune',
'Pune Bangalore Highway, Pune',
'Kondhwa Pisoli Road, Pune',
'Hadapsar Mundhwa Road, Pune',
'Kharadi Bypass, Pune',
'Wagholi Lohegaon Road, Pune',
'Viman Nagar New Airport Road, Pune',
'Yerwada Kalyani Nagar Road, Pune',
'Koregaon Park Mundhwa Road, Pune',
'Magarpatta Hadapsar Road, Pune',
'Pimple Saudagar Kate Wasti, Pune',
'Wakad Datta Mandir Road, Pune',
'Baner Sus Road, Pune',
'Aundh Ward No 8, Pune',
'Kothrud Ward No 9, Pune',
'Hadapsar Ward No 10, Pune',
'Viman Nagar Ward No 11, Pune',
'Kalyani Nagar Ward No 12, Pune',
'Koregaon Park Ward No 13, Pune',
'Yerwada Ward No 14, Pune',
'Wakad Ward No 15, Pune',
'Baner Ward No 16, Pune',
'Pashan Ward No 17, Pune',
'Bavdhan Ward No 18, Pune',
'Warje Ward No 19, Pune',
'Katraj Ward No 20, Pune',
'Bibwewadi Ward No 21, Pune',
'Kondhwa Ward No 22, Pune',
'Wanorie Ward No 23, Pune',
'Pimpri Ward No 24, Pune',
'Chinchwad Ward No 25, Pune',
'Hinjewadi Ward No 26, Pune',
'Magarpatta Ward No 27, Pune',
'Kharadi Ward No 28, Pune',
'Deccan Gymkhana Ward No 29, Pune',
'Shivaji Nagar Ward No 30, Pune',
'Sadashiv Peth Ward No 31, Pune',
'Erandwane Ward No 32, Pune',
'Karve Nagar Ward No 33, Pune',
'Parvati Ward No 34, Pune',
'Swargate Ward No 35, Pune',
'Camp Ward No 36, Pune',
'Kasba Peth Ward No 37, Pune',
'Bhawani Peth Ward No 38, Pune',
'Sahakar Nagar Ward No 39, Pune',
'Dhankawadi Ward No 40, Pune',
'Ambegaon Ward No 41, Pune',
'Undri Ward No 42, Pune',
'Lohegaon Ward No 43, Pune',
'Wagholi Ward No 44, Pune',
'Vishrantwadi Ward No 45, Pune',
'Dhanori Ward No 46, Pune',
'Tingre Nagar Ward No 47, Pune',
'Keshav Nagar Ward No 48, Pune',
'Manjri Ward No 49, Pune',
'Phursungi Ward No 50, Pune',
'Sasane Nagar Ward No 51, Pune',
'Ramtekdi Ward No 52, Pune',
'Sopan Baug Ward No 53, Pune',
'Sangamvadi Ward No 54, Pune',
'Shastri Nagar Ward No 55, Pune',
'Sancheti Nagar Ward No 56, Pune',
'Shivane Ward No 57, Pune',
'Uttam Nagar Ward No 58, Pune',
'Narhe Ward No 59, Pune',
'Khadakwasla Ward No 60, Pune',
'Hingne Khurd Ward No 61, Pune',
'Kirkatwadi Ward No 62, Pune',
'Vadgaon Budruk Ward No 63, Pune',
'Vadgaon Sheri Ward No 64, Pune',
'Kondhwa Budruk Ward No 65, Pune',
'Kondhwa Khurd Ward No 66, Pune',
'Balaji Nagar Ward No 67, Pune',
'Anand Nagar Ward No 68, Pune',
'Manik Baug Ward No 69, Pune',
'Hingane Mala Ward No 70, Pune',
'Pune Okayama Friendship Garden, Pune',
'Pune Zoo, Pune',
'Rajiv Gandhi Zoological Park, Pune',
'Snake Park, Pune',
'Bird Valley, Pune',
'Seven Wonders Park, Pune',
'Late Sanjay Mahadeo Nimhan Garden, Pune',
'Peshwe Energy Park, Pune',
'Vande Mataram Garden, Pune',
'Chhatrapati Shivaji Maharaj Garden, Pune',
'Raja Dinkar Kelkar Museum Garden, Pune',
'Tribal Museum Area, Pune',
'Bhimashankar Wildlife Sanctuary Entrance, Pune',
'Mastani Lake, Pune',
'Pune Metro Line 1 Area, Pune',
'Pune Metro Line 2 Area, Pune',
'Pune Metro Line 3 Area, Pune',
'Pune International Airport Area, Pune',
'Pune Junction, Pune',
'Shivajinagar Station, Pune',
'Khadki Station, Pune',
'Pimpri Station, Pune',
'Chinchwad Station, Pune',
'Kasarwadi Station, Pune',
'Dapodi Station, Pune',
'Akurdi Station, Pune',
'Dehu Road Station, Pune',
'Begdewadi Station, Pune',
'Ghorawadi Station, Pune',
'Talegaon Station, Pune',
'Vadgaon Station, Pune',
'Kanhe Station, Pune',
'Kamshet Station, Pune',
'Malavli Station, Pune',
'Lonavala Station, Pune',
'Hadapsar Station, Pune',
'Manjari Station, Pune',
'Loni Station, Pune',
'Uruli Station, Pune',
'Yevat Station, Pune',
'Kedgaon Station, Pune',
'Patas Station, Pune',
'Daund Station, Pune',
'Baramati Station, Pune',
'Phaltan Station, Pune',
'Jejuri Station, Pune',
'Saswad Station, Pune',
'Pune Bus Stand, Pune',
'Swargate Bus Stand, Pune',
'Shivajinagar Bus Stand, Pune',
'Pimpri Chinchwad Bus Stand, Pune',
'Katraj Bus Stand, Pune',
'Hadapsar Bus Stand, Pune',
'Kothrud Bus Stand, Pune',
'Baner Bus Stand, Pune',
'Aundh Bus Stand, Pune',
'Hinjewadi Bus Stand, Pune',
'Wakad Bus Stand, Pune',
'Viman Nagar Bus Stand, Pune',
'Kalyani Nagar Bus Stand, Pune',
'Koregaon Park Bus Stand, Pune',
'Yerwada Bus Stand, Pune',
'Magarpatta Bus Stand, Pune',
'Kharadi Bus Stand, Pune',
'Wagholi Bus Stand, Pune',
'Lohegaon Bus Stand, Pune',
'Vishrantwadi Bus Stand, Pune',
'Dhanori Bus Stand, Pune',
'Tingre Nagar Bus Stand, Pune',
'Keshav Nagar Bus Stand, Pune',
'Manjri Bus Stand, Pune',
'Phursungi Bus Stand, Pune',
'Sasane Nagar Bus Stand, Pune',
'Ramtekdi Bus Stand, Pune',
'Sopan Baug Bus Stand, Pune',
'Sangamvadi Bus Stand, Pune',
'Shastri Nagar Bus Stand, Pune',
'Sancheti Nagar Bus Stand, Pune',
'Shivane Bus Stand, Pune',
'Uttam Nagar Bus Stand, Pune',
'Narhe Bus Stand, Pune',
'Khadakwasla Bus Stand, Pune',
'Hingne Khurd Bus Stand, Pune',
'Kirkatwadi Bus Stand, Pune',
'Vadgaon Budruk Bus Stand, Pune',
'Vadgaon Sheri Bus Stand, Pune',
'Kondhwa Budruk Bus Stand, Pune',
'Kondhwa Khurd Bus Stand, Pune',
'Balaji Nagar Bus Stand, Pune',
'Anand Nagar Bus Stand, Pune',
'Manik Baug Bus Stand, Pune',
'Hingane Mala Bus Stand, Pune',
'Pune Racecourse, Pune',
'Pune Golf Club, Pune',
'Pune University Campus, Pune',
'Pune IT Park, Pune',
'Pune MIDC, Pune',
'Pune RTO, Pune',
'Pune Central Mall, Pune',
'Pune Fashion Street, Pune',
'Pune Clover Park, Pune',
'Pune Alandi Devachi, Pune',
'Pune Chakan MIDC, Pune',
'Pune Talegaon MIDC, Pune',
'Pune Ranjangaon MIDC, Pune',
'Pune Hinjawadi MIDC, Pune',
'Pune Talawade MIDC, Pune',
'Pune Baramati MIDC, Pune',
'Pune Jejuri MIDC, Pune',
'Pune Saswad MIDC, Pune',
'Pune Purandar MIDC, Pune',
'Pune Daund MIDC, Pune',
'Pune Phaltan MIDC, Pune',
'Pune Khed MIDC, Pune',
'Pune Shikrapur MIDC, Pune',
'Pune Koregaon Bhima MIDC, Pune',
'Pune Sanaswadi MIDC, Pune',
'Pune Lonikand MIDC, Pune',
'Pune Wagholi MIDC, Pune',
'Pune Chakan Industrial Area, Pune',
'Pune Talegaon Industrial Area, Pune',
'Pune Ranjangaon Industrial Area, Pune',
'Pune Hinjawadi Industrial Area, Pune',
'Pune Talawade Industrial Area, Pune',
'Pune Baramati Industrial Area, Pune',
'Pune Jejuri Industrial Area, Pune',
'Pune Saswad Industrial Area, Pune',
'Pune Purandar Industrial Area, Pune',
'Pune Daund Industrial Area, Pune',
'Pune Phaltan Industrial Area, Pune',
'Pune Khed Industrial Area, Pune',
'Pune Shikrapur Industrial Area, Pune',
'Pune Koregaon Bhima Industrial Area, Pune',
'Pune Sanaswadi Industrial Area, Pune',
'Pune Lonikand Industrial Area, Pune',
'Pune Wagholi Industrial Area, Pune',
'Pune Chakan SEZ, Pune',
'Pune Talegaon SEZ, Pune',
'Pune Ranjangaon SEZ, Pune',
'Pune Hinjawadi SEZ, Pune',
'Pune Talawade SEZ, Pune',
'Pune Baramati SEZ, Pune',
'Pune Jejuri SEZ, Pune',
'Pune Saswad SEZ, Pune',
'Pune Purandar SEZ, Pune',
'Pune Daund SEZ, Pune',
'Pune Phaltan SEZ, Pune',
'Pune Khed SEZ, Pune',
'Pune Shikrapur SEZ, Pune',
'Pune Koregaon Bhima SEZ, Pune',
'Pune Sanaswadi SEZ, Pune',
'Pune Lonikand SEZ, Pune',
'Pune Wagholi SEZ, Pune',
'Pune Chakan IT Park, Pune',
'Pune Talegaon IT Park, Pune',
'Pune Ranjangaon IT Park, Pune',
'Pune Hinjawadi IT Park, Pune',
'Pune Talawade IT Park, Pune',
'Pune Baramati IT Park, Pune',
'Pune Jejuri IT Park, Pune',
'Pune Saswad IT Park, Pune',
'Pune Purandar IT Park, Pune',
'Pune Daund IT Park, Pune',
'Pune Phaltan IT Park, Pune',
'Pune Khed IT Park, Pune',
'Pune Shikrapur IT Park, Pune',
'Pune Koregaon Bhima IT Park, Pune',
'Pune Sanaswadi IT Park, Pune',
'Pune Lonikand IT Park, Pune',
'Pune Wagholi IT Park, Pune',
'Pune Chakan Biotech Park, Pune',
'Pune Talegaon Biotech Park, Pune',
'Pune Ranjangaon Biotech Park, Pune',
'Pune Hinjawadi Biotech Park, Pune',
'Pune Talawade Biotech Park, Pune',
'Pune Baramati Biotech Park, Pune',
'Pune Jejuri Biotech Park, Pune',
'Pune Saswad Biotech Park, Pune',
'Pune Purandar Biotech Park, Pune',
'Pune Daund Biotech Park, Pune',
'Pune Phaltan Biotech Park, Pune',
'Pune Khed Biotech Park, Pune',
'Pune Shikrapur Biotech Park, Pune',
'Pune Koregaon Bhima Biotech Park, Pune',
'Pune Sanaswadi Biotech Park, Pune',
'Pune Lonikand Biotech Park, Pune',
'Pune Wagholi Biotech Park, Pune',
'Pune Chakan Logistics Park, Pune',
'Pune Talegaon Logistics Park, Pune',
'Pune Ranjangaon Logistics Park, Pune',
'Pune Hinjawadi Logistics Park, Pune',
'Pune Talawade Logistics Park, Pune',
'Pune Baramati Logistics Park, Pune',
'Pune Jejuri Logistics Park, Pune',
'Pune Saswad Logistics Park, Pune',
'Pune Purandar Logistics Park, Pune',
'Pune Daund Logistics Park, Pune',
'Pune Phaltan Logistics Park, Pune',
'Pune Khed Logistics Park, Pune',
'Pune Shikrapur Logistics Park, Pune',
'Pune Koregaon Bhima Logistics Park, Pune',
'Pune Sanaswadi Logistics Park, Pune',
'Pune Lonikand Logistics Park, Pune',
'Pune Wagholi Logistics Park, Pune',
'Pune Chakan Auto Park, Pune',
'Pune Talegaon Auto Park, Pune',
'Pune Ranjangaon Auto Park, Pune',
'Pune Hinjawadi Auto Park, Pune',
'Pune Talawade Auto Park, Pune',
'Pune Baramati Auto Park, Pune',
'Pune Jejuri Auto Park, Pune',
'Pune Saswad Auto Park, Pune',
'Pune Purandar Auto Park, Pune',
'Pune Daund Auto Park, Pune',
'Pune Phaltan Auto Park, Pune',
'Pune Khed Auto Park, Pune',
'Pune Shikrapur Auto Park, Pune',
'Pune Koregaon Bhima Auto Park, Pune',
'Pune Sanaswadi Auto Park, Pune',
'Pune Lonikand Auto Park, Pune',
'Pune Wagholi Auto Park, Pune',
'Pune Chakan Textile Park, Pune',
'Pune Talegaon Textile Park, Pune',
'Pune Ranjangaon Textile Park, Pune',
'Pune Hinjawadi Textile Park, Pune',
'Pune Talawade Textile Park, Pune',
'Pune Baramati Textile Park, Pune',
'Pune Jejuri Textile Park, Pune',
'Pune Saswad Textile Park, Pune',
'Pune Purandar Textile Park, Pune',
'Pune Daund Textile Park, Pune',
'Pune Phaltan Textile Park, Pune',
'Pune Khed Textile Park, Pune',
'Pune Shikrapur Textile Park, Pune',
'Pune Koregaon Bhima Textile Park, Pune',
'Pune Sanaswadi Textile Park, Pune',
'Pune Lonikand Textile Park, Pune',
'Pune Wagholi Textile Park, Pune',
'Pune Chakan Food Park, Pune',
'Pune Talegaon Food Park, Pune',
'Pune Ranjangaon Food Park, Pune',
'Pune Hinjawadi Food Park, Pune',
'Pune Talawade Food Park, Pune',
'Pune Baramati Food Park, Pune',
'Pune Jejuri Food Park, Pune',
'Pune Saswad Food Park, Pune',
'Pune Purandar Food Park, Pune',
'Pune Daund Food Park, Pune',
'Pune Phaltan Food Park, Pune',
'Pune Khed Food Park, Pune',
'Pune Shikrapur Food Park, Pune',
'Pune Koregaon Bhima Food Park, Pune',
'Pune Sanaswadi Food Park, Pune',
'Pune Lonikand Food Park, Pune',
'Pune Wagholi Food Park, Pune',
'Pune Chakan Chemical Park, Pune',
'Pune Talegaon Chemical Park, Pune',
'Pune Ranjangaon Chemical Park, Pune',
'Pune Hinjawadi Chemical Park, Pune',
'Pune Talawade Chemical Park, Pune',
'Pune Baramati Chemical Park, Pune',
'Pune Jejuri Chemical Park, Pune',
'Pune Saswad Chemical Park, Pune',
'Pune Purandar Chemical Park, Pune',
'Pune Daund Chemical Park, Pune',
'Pune Phaltan Chemical Park, Pune',
'Pune Khed Chemical Park, Pune',
'Pune Shikrapur Chemical Park, Pune',
'Pune Koregaon Bhima Chemical Park, Pune',
'Pune Sanaswadi Chemical Park, Pune',
'Pune Lonikand Chemical Park, Pune',
'Pune Wagholi Chemical Park, Pune',
'Pune Chakan Pharma Park, Pune',
'Pune Talegaon Pharma Park, Pune',
'Pune Ranjangaon Pharma Park, Pune',
'Pune Hinjawadi Pharma Park, Pune',
'Pune Talawade Pharma Park, Pune',
'Pune Baramati Pharma Park, Pune',
'Pune Jejuri Pharma Park, Pune',
'Pune Saswad Pharma Park, Pune',
'Pune Purandar Pharma Park, Pune',
'Pune Daund Pharma Park, Pune',
'Pune Phaltan Pharma Park, Pune',
'Pune Khed Pharma Park, Pune',
'Pune Shikrapur Pharma Park, Pune',
'Pune Koregaon Bhima Pharma Park, Pune',
'Pune Sanaswadi Pharma Park, Pune',
'Pune Lonikand Pharma Park, Pune',
'Pune Wagholi Pharma Park, Pune',
'Pune Chakan Electronics Park, Pune',
'Pune Talegaon Electronics Park, Pune',
'Pune Ranjangaon Electronics Park, Pune',
'Pune Hinjawadi Electronics Park, Pune',
'Pune Talawade Electronics Park, Pune',
'Pune Baramati Electronics Park, Pune',
'Pune Jejuri Electronics Park, Pune',
'Pune Saswad Electronics Park, Pune',
'Pune Purandar Electronics Park, Pune',
'Pune Daund Electronics Park, Pune',
'Pune Phaltan Electronics Park, Pune',
'Pune Khed Electronics Park, Pune',
'Pune Shikrapur Electronics Park, Pune',
'Pune Koregaon Bhima Electronics Park, Pune',
'Pune Sanaswadi Electronics Park, Pune',
'Pune Lonikand Electronics Park, Pune',
'Pune Wagholi Electronics Park, Pune',
'Pune Chakan Aerospace Park, Pune',
'Pune Talegaon Aerospace Park, Pune',
'Pune Ranjangaon Aerospace Park, Pune',
'Pune Hinjawadi Aerospace Park, Pune',
'Pune Talawade Aerospace Park, Pune',
'Pune Baramati Aerospace Park, Pune',
'Pune Jejuri Aerospace Park, Pune',
'Pune Saswad Aerospace Park, Pune',
'Pune Purandar Aerospace Park, Pune',
'Pune Daund Aerospace Park, Pune',
'Pune Phaltan Aerospace Park, Pune',
'Pune Khed Aerospace Park, Pune',
'Pune Shikrapur Aerospace Park, Pune',
'Pune Koregaon Bhima Aerospace Park, Pune',
'Pune Sanaswadi Aerospace Park, Pune',
'Pune Lonikand Aerospace Park, Pune',
'Pune Wagholi Aerospace Park, Pune',
'Pune Chakan Renewable Energy Park, Pune',
'Pune Talegaon Renewable Energy Park, Pune',
'Pune Ranjangaon Renewable Energy Park, Pune',
'Pune Hinjawadi Renewable Energy Park, Pune',
'Pune Talawade Renewable Energy Park, Pune',
'Pune Baramati Renewable Energy Park, Pune',
'Pune Jejuri Renewable Energy Park, Pune',
'Pune Saswad Renewable Energy Park, Pune',
'Pune Purandar Renewable Energy Park, Pune',
'Pune Daund Renewable Energy Park, Pune',
'Pune Phaltan Renewable Energy Park, Pune',
'Pune Khed Renewable Energy Park, Pune',
'Pune Shikrapur Renewable Energy Park, Pune',
'Pune Koregaon Bhima Renewable Energy Park, Pune',
'Pune Sanaswadi Renewable Energy Park, Pune',
'Pune Lonikand Renewable Energy Park, Pune',
'Pune Wagholi Renewable Energy Park, Pune',
'Pune Chakan Green Energy Park, Pune',
'Pune Talegaon Green Energy Park, Pune',
'Pune Ranjangaon Green Energy Park, Pune',
'Pune Hinjawadi Green Energy Park, Pune',
'Pune Talawade Green Energy Park, Pune',
'Pune Baramati Green Energy Park, Pune',
'Pune Jejuri Green Energy Park, Pune',
'Pune Saswad Green Energy Park, Pune',
'Pune Purandar Green Energy Park, Pune',
'Pune Daund Green Energy Park, Pune',
'Pune Phaltan Green Energy Park, Pune',
'Pune Khed Green Energy Park, Pune',
'Pune Shikrapur Green Energy Park, Pune',
'Pune Koregaon Bhima Green Energy Park, Pune',
'Pune Sanaswadi Green Energy Park, Pune',
'Pune Lonikand Green Energy Park, Pune',
'Pune Wagholi Green Energy Park, Pune',
'Pune Chakan Smart City, Pune',
'Pune Talegaon Smart City, Pune',
'Pune Ranjangaon Smart City, Pune',
'Pune Hinjawadi Smart City, Pune',
'Pune Talawade Smart City, Pune',
'Pune Baramati Smart City, Pune',
'Pune Jejuri Smart City, Pune',
'Pune Saswad Smart City, Pune',
'Pune Purandar Smart City, Pune',
'Pune Daund Smart City, Pune',
'Pune Phaltan Smart City, Pune',
'Pune Khed Smart City, Pune',
'Pune Shikrapur Smart City, Pune',
'Pune Koregaon Bhima Smart City, Pune',
'Pune Sanaswadi Smart City, Pune',
'Pune Lonikand Smart City, Pune',
'Pune Wagholi Smart City, Pune',
'Pune Chakan Innovation Hub, Pune',
'Pune Talegaon Innovation Hub, Pune',
'Pune Ranjangaon Innovation Hub, Pune',
'Pune Hinjawadi Innovation Hub, Pune',
'Pune Talawade Innovation Hub, Pune',
'Pune Baramati Innovation Hub, Pune',
'Pune Jejuri Innovation Hub, Pune',
'Pune Saswad Innovation Hub, Pune',
'Pune Purandar Innovation Hub, Pune',
'Pune Daund Innovation Hub, Pune',
'Pune Phaltan Innovation Hub, Pune',
'Pune Khed Innovation Hub, Pune',
'Pune Shikrapur Innovation Hub, Pune',
'Pune Koregaon Bhima Innovation Hub, Pune',
'Pune Sanaswadi Innovation Hub, Pune',
'Pune Lonikand Innovation Hub, Pune',
'Pune Wagholi Innovation Hub, Pune',
'Pune Chakan Startup Hub, Pune',
'Pune Talegaon Startup Hub, Pune',
'Pune Ranjangaon Startup Hub, Pune',
'Pune Hinjawadi Startup Hub, Pune',
'Pune Talawade Startup Hub, Pune',
'Pune Baramati Startup Hub, Pune',
'Pune Jejuri Startup Hub, Pune',
'Pune Saswad Startup Hub, Pune',
'Pune Purandar Startup Hub, Pune',
'Pune Daund Startup Hub, Pune',
'Pune Phaltan Startup Hub, Pune',
'Pune Khed Startup Hub, Pune',
'Pune Shikrapur Startup Hub, Pune',
'Pune Koregaon Bhima Startup Hub, Pune',
'Pune Sanaswadi Startup Hub, Pune',
'Pune Lonikand Startup Hub, Pune',
'Pune Wagholi Startup Hub, Pune',
'Pune Chakan Incubation Centre, Pune',
'Pune Talegaon Incubation Centre, Pune',
'Pune Ranjangaon Incubation Centre, Pune',
'Pune Hinjawadi Incubation Centre, Pune',
'Pune Talawade Incubation Centre, Pune',
'Pune Baramati Incubation Centre, Pune',
'Pune Jejuri Incubation Centre, Pune',
'Pune Saswad Incubation Centre, Pune',
'Pune Purandar Incubation Centre, Pune',
'Pune Daund Incubation Centre, Pune',
'Pune Phaltan Incubation Centre, Pune',
'Pune Khed Incubation Centre, Pune',
'Pune Shikrapur Incubation Centre, Pune',
'Pune Koregaon Bhima Incubation Centre, Pune',
'Pune Sanaswadi Incubation Centre, Pune',
'Pune Lonikand Incubation Centre, Pune',
'Pune Wagholi Incubation Centre, Pune',
'Pune Chakan Research Park, Pune',
'Pune Talegaon Research Park, Pune',
'Pune Ranjangaon Research Park, Pune',
'Pune Hinjawadi Research Park, Pune',
'Pune Talawade Research Park, Pune',
'Pune Baramati Research Park, Pune',
'Pune Jejuri Research Park, Pune',
'Pune Saswad Research Park, Pune',
'Pune Purandar Research Park, Pune',
'Pune Daund Research Park, Pune',
'Pune Phaltan Research Park, Pune',
'Pune Khed Research Park, Pune',
'Pune Shikrapur Research Park, Pune',
'Pune Koregaon Bhima Research Park, Pune',
'Pune Sanaswadi Research Park, Pune',
'Pune Lonikand Research Park, Pune',
'Pune Wagholi Research Park, Pune',
'Pune Chakan Technology Park, Pune',
'Pune Talegaon Technology Park, Pune',
'Pune Ranjangaon Technology Park, Pune',
'Pune Hinjawadi Technology Park, Pune',
'Pune Talawade Technology Park, Pune',
'Pune Baramati Technology Park, Pune',
'Pune Jejuri Technology Park, Pune',
'Pune Saswad Technology Park, Pune',
'Pune Purandar Technology Park, Pune',
'Pune Daund Technology Park, Pune',
'Pune Phaltan Technology Park, Pune',
'Pune Khed Technology Park, Pune',
'Pune Shikrapur Technology Park, Pune',
'Pune Koregaon Bhima Technology Park, Pune',
'Pune Sanaswadi Technology Park, Pune',
'Pune Lonikand Technology Park, Pune',
'Pune Wagholi Technology Park, Pune',
'Pune Chakan Science Park, Pune',
'Pune Talegaon Science Park, Pune',
'Pune Ranjangaon Science Park, Pune',
'Pune Hinjawadi Science Park, Pune',
'Pune Talawade Science Park, Pune',
'Pune Baramati Science Park, Pune',
'Pune Jejuri Science Park, Pune',
'Pune Saswad Science Park, Pune',
'Pune Purandar Science Park, Pune',
'Pune Daund Science Park, Pune',
'Pune Phaltan Science Park, Pune',
'Pune Khed Science Park, Pune',
'Pune Shikrapur Science Park, Pune',
'Pune Koregaon Bhima Science Park, Pune',
'Pune Sanaswadi Science Park, Pune',
'Pune Lonikand Science Park, Pune',
'Pune Wagholi Science Park, Pune',
'Pune Chakan Engineering Park, Pune',
'Pune Talegaon Engineering Park, Pune',
'Pune Ranjangaon Engineering Park, Pune',
'Pune Hinjawadi Engineering Park, Pune',
'Pune Talawade Engineering Park, Pune',
'Pune Baramati Engineering Park, Pune',
'Pune Jejuri Engineering Park, Pune',
'Pune Saswad Engineering Park, Pune',
'Pune Purandar Engineering Park, Pune',
'Pune Daund Engineering Park, Pune',
'Pune Phaltan Engineering Park, Pune',
'Pune Khed Engineering Park, Pune',
'Pune Shikrapur Engineering Park, Pune',
'Pune Koregaon Bhima Engineering Park, Pune',
'Pune Sanaswadi Engineering Park, Pune',
'Pune Lonikand Engineering Park, Pune',
'Pune Wagholi Engineering Park, Pune',
'Pune Chakan Manufacturing Hub, Pune',
'Pune Talegaon Manufacturing Hub, Pune',
'Pune Ranjangaon Manufacturing Hub, Pune',
'Pune Hinjawadi Manufacturing Hub, Pune',
'Pune Talawade Manufacturing Hub, Pune',
'Pune Baramati Manufacturing Hub, Pune',
'Pune Jejuri Manufacturing Hub, Pune',
'Pune Saswad Manufacturing Hub, Pune',
'Pune Purandar Manufacturing Hub, Pune',
'Pune Daund Manufacturing Hub, Pune',
'Pune Phaltan Manufacturing Hub, Pune',
'Pune Khed Manufacturing Hub, Pune',
'Pune Shikrapur Manufacturing Hub, Pune',
'Pune Koregaon Bhima Manufacturing Hub, Pune',
'Pune Sanaswadi Manufacturing Hub, Pune',
'Pune Lonikand Manufacturing Hub, Pune',
'Pune Wagholi Manufacturing Hub, Pune',
'Pune Chakan Industrial Corridor, Pune',
'Pune Talegaon Industrial Corridor, Pune',
'Pune Ranjangaon Industrial Corridor, Pune',
'Pune Hinjawadi Industrial Corridor, Pune',
'Pune Talawade Industrial Corridor, Pune',
'Pune Baramati Industrial Corridor, Pune',
'Pune Jejuri Industrial Corridor, Pune',
'Pune Saswad Industrial Corridor, Pune',
'Pune Purandar Industrial Corridor, Pune',
'Pune Daund Industrial Corridor, Pune',
'Pune Phaltan Industrial Corridor, Pune',
'Pune Khed Industrial Corridor, Pune',
'Pune Shikrapur Industrial Corridor, Pune',
'Pune Koregaon Bhima Industrial Corridor, Pune',
'Pune Sanaswadi Industrial Corridor, Pune',
'Pune Lonikand Industrial Corridor, Pune',
'Pune Wagholi Industrial Corridor, Pune',
'Pune Chakan Economic Zone, Pune',
'Pune Talegaon Economic Zone, Pune',
'Pune Ranjangaon Economic Zone, Pune',
'Pune Hinjawadi Economic Zone, Pune',
'Pune Talawade Economic Zone, Pune',
'Pune Baramati Economic Zone, Pune',
'Pune Jejuri Economic Zone, Pune',
'Pune Saswad Economic Zone, Pune',
'Pune Purandar Economic Zone, Pune',
'Pune Daund Economic Zone, Pune',
'Pune Phaltan Economic Zone, Pune',
'Pune Khed Economic Zone, Pune',
'Pune Shikrapur Economic Zone, Pune',
'Pune Koregaon Bhima Economic Zone, Pune',
'Pune Sanaswadi Economic Zone, Pune',
'Pune Lonikand Economic Zone, Pune',
'Pune Wagholi Economic Zone, Pune',
'Pune Chakan Trade Zone, Pune',
'Pune Talegaon Trade Zone, Pune',
'Pune Ranjangaon Trade Zone, Pune',
'Pune Hinjawadi Trade Zone, Pune',
'Pune Talawade Trade Zone, Pune',
'Pune Baramati Trade Zone, Pune',
'Pune Jejuri Trade Zone, Pune',
'Pune Saswad Trade Zone, Pune',
'Pune Purandar Trade Zone, Pune',
'Pune Daund Trade Zone, Pune',
'Pune Phaltan Trade Zone, Pune',
'Pune Khed Trade Zone, Pune',
'Pune Shikrapur Trade Zone, Pune',
'Pune Koregaon Bhima Trade Zone, Pune',
'Pune Sanaswadi Trade Zone, Pune',
'Pune Lonikand Trade Zone, Pune',
'Pune Wagholi Trade Zone, Pune',
'Pune Chakan Business Park, Pune',
'Pune Talegaon Business Park, Pune',
'Pune Ranjangaon Business Park, Pune',
'Pune Hinjawadi Business Park, Pune',
'Pune Talawade Business Park, Pune',
'Pune Baramati Business Park, Pune',
'Pune Jejuri Business Park, Pune',
'Pune Saswad Business Park, Pune',
'Pune Purandar Business Park, Pune',
'Pune Daund Business Park, Pune',
'Pune Phaltan Business Park, Pune',
'Pune Khed Business Park, Pune',
'Pune Shikrapur Business Park, Pune',
'Pune Koregaon Bhima Business Park, Pune',
'Pune Sanaswadi Business Park, Pune',
'Pune Lonikand Business Park, Pune',
'Pune Wagholi Business Park, Pune',
'Pune Chakan Commercial Hub, Pune',
'Pune Talegaon Commercial Hub, Pune',
'Pune Ranjangaon Commercial Hub, Pune',
'Pune Hinjawadi Commercial Hub, Pune',
'Pune Talawade Commercial Hub, Pune',
'Pune Baramati Commercial Hub, Pune',
'Pune Jejuri Commercial Hub, Pune',
'Pune Saswad Commercial Hub, Pune',
'Pune Purandar Commercial Hub, Pune',
'Pune Daund Commercial Hub, Pune',
'Pune Phaltan Commercial Hub, Pune',
'Pune Khed Commercial Hub, Pune',
'Pune Shikrapur Commercial Hub, Pune',
'Pune Koregaon Bhima Commercial Hub, Pune',
'Pune Sanaswadi Commercial Hub, Pune',
'Pune Lonikand Commercial Hub, Pune',
'Pune Wagholi Commercial Hub, Pune',
'Pune Chakan Retail Zone, Pune',
'Pune Talegaon Retail Zone, Pune',
'Pune Ranjangaon Retail Zone, Pune',
'Pune Hinjawadi Retail Zone, Pune',
'Pune Talawade Retail Zone, Pune',
'Pune Baramati Retail Zone, Pune',
'Pune Jejuri Retail Zone, Pune',
'Pune Saswad Retail Zone, Pune',
'Pune Purandar Retail Zone, Pune',
'Pune Daund Retail Zone, Pune',
'Pune Phaltan Retail Zone, Pune',
'Pune Khed Retail Zone, Pune',
'Pune Shikrapur Retail Zone, Pune',
'Pune Koregaon Bhima Retail Zone, Pune',
'Pune Sanaswadi Retail Zone, Pune',
'Pune Lonikand Retail Zone, Pune',
'Pune Wagholi Retail Zone, Pune',
'Pune Chakan Education Hub, Pune',
'Pune Talegaon Education Hub, Pune',
'Pune Ranjangaon Education Hub, Pune',
'Pune Hinjawadi Education Hub, Pune',
'Pune Talawade Education Hub, Pune',
'Pune Baramati Education Hub, Pune',
'Pune Jejuri Education Hub, Pune',
'Pune Saswad Education Hub, Pune',
'Pune Purandar Education Hub, Pune',
'Pune Daund Education Hub, Pune',
'Pune Phaltan Education Hub, Pune',
'Pune Khed Education Hub, Pune',
'Pune Shikrapur Education Hub, Pune',
'Pune Koregaon Bhima Education Hub, Pune',
'Pune Sanaswadi Education Hub, Pune',
'Pune Lonikand Education Hub, Pune',
'Pune Wagholi Education Hub, Pune',
'Pune Chakan Healthcare Hub, Pune',
'Pune Talegaon Healthcare Hub, Pune',
'Pune Ranjangaon Healthcare Hub, Pune',
'Pune Hinjawadi Healthcare Hub, Pune',
'Pune Talawade Healthcare Hub, Pune',
'Pune Baramati Healthcare Hub, Pune',
'Pune Jejuri Healthcare Hub, Pune',
'Pune Saswad Healthcare Hub, Pune',
'Pune Purandar Healthcare Hub, Pune',
'Pune Daund Healthcare Hub, Pune',
'Pune Phaltan Healthcare Hub, Pune',
'Pune Khed Healthcare Hub, Pune',
'Pune Shikrapur Healthcare Hub, Pune',
'Pune Koregaon Bhima Healthcare Hub, Pune',
'Pune Sanaswadi Healthcare Hub, Pune',
'Pune Lonikand Healthcare Hub, Pune',
'Pune Wagholi Healthcare Hub, Pune',
'Pune Chakan Sports Hub, Pune',
'Pune Talegaon Sports Hub, Pune',
'Pune Ranjangaon Sports Hub, Pune',
'Pune Hinjawadi Sports Hub, Pune',
'Pune Talawade Sports Hub, Pune',
'Pune Baramati Sports Hub, Pune',
'Pune Jejuri Sports Hub, Pune',
'Pune Saswad Sports Hub, Pune',
'Pune Purandar Sports Hub, Pune',
'Pune Daund Sports Hub, Pune',
'Pune Phaltan Sports Hub, Pune',
'Pune Khed Sports Hub, Pune',
'Pune Shikrapur Sports Hub, Pune',
'Pune Koregaon Bhima Sports Hub, Pune',
'Pune Sanaswadi Sports Hub, Pune',
'Pune Lonikand Sports Hub, Pune',
'Pune Wagholi Sports Hub, Pune',
'Pune Chakan Cultural Hub, Pune',
'Pune Talegaon Cultural Hub, Pune',
'Pune Ranjangaon Cultural Hub, Pune',
'Pune Hinjawadi Cultural Hub, Pune',
'Pune Talawade Cultural Hub, Pune',
'Pune Baramati Cultural Hub, Pune',
'Pune Jejuri Cultural Hub, Pune',
'Pune Saswad Cultural Hub, Pune',
'Pune Purandar Cultural Hub, Pune',
'Pune Daund Cultural Hub, Pune',
'Pune Phaltan Cultural Hub, Pune',
'Pune Khed Cultural Hub, Pune',
'Pune Shikrapur Cultural Hub, Pune',
'Pune Koregaon Bhima Cultural Hub, Pune',
'Pune Sanaswadi Cultural Hub, Pune',
'Pune Lonikand Cultural Hub, Pune',
'Pune Wagholi Cultural Hub, Pune',
'Pune Chakan Tourism Hub, Pune',
'Pune Talegaon Tourism Hub, Pune',
'Pune Ranjangaon Tourism Hub, Pune',
'Pune Hinjawadi Tourism Hub, Pune',
'Pune Talawade Tourism Hub, Pune',
'Pune Baramati Tourism Hub, Pune',
'Pune Jejuri Tourism Hub, Pune',
'Pune Saswad Tourism Hub, Pune',
'Pune Purandar Tourism Hub, Pune',
'Pune Daund Tourism Hub, Pune',
'Pune Phaltan Tourism Hub, Pune',
'Pune Khed Tourism Hub, Pune',
'Pune Shikrapur Tourism Hub, Pune',
'Pune Koregaon Bhima Tourism Hub, Pune',
'Pune Sanaswadi Tourism Hub, Pune',
'Pune Lonikand Tourism Hub, Pune',
'Pune Wagholi Tourism Hub, Pune',
'Pune Chakan Heritage Zone, Pune',
'Pune Talegaon Heritage Zone, Pune',
'Pune Ranjangaon Heritage Zone, Pune',
'Pune Hinjawadi Heritage Zone, Pune',
'Pune Talawade Heritage Zone, Pune',
'Pune Baramati Heritage Zone, Pune',
'Pune Jejuri Heritage Zone, Pune',
'Pune Saswad Heritage Zone, Pune',
'Pune Purandar Heritage Zone, Pune',
'Pune Daund Heritage Zone, Pune',
'Pune Phaltan Heritage Zone, Pune',
'Pune Khed Heritage Zone, Pune',
'Pune Shikrapur Heritage Zone, Pune',
'Pune Koregaon Bhima Heritage Zone, Pune',
'Pune Sanaswadi Heritage Zone, Pune',
'Pune Lonikand Heritage Zone, Pune',
'Pune Wagholi Heritage Zone, Pune',
'Pune Chakan Eco Zone, Pune',
'Pune Talegaon Eco Zone, Pune',
'Pune Ranjangaon Eco Zone, Pune',
'Pune Hinjawadi Eco Zone, Pune',
'Pune Talawade Eco Zone, Pune',
'Pune Baramati Eco Zone, Pune',
'Pune Jejuri Eco Zone, Pune',
'Pune Saswad Eco Zone, Pune',
'Pune Purandar Eco Zone, Pune',
'Pune Daund Eco Zone, Pune',
'Pune Phaltan Eco Zone, Pune',
'Pune Khed Eco Zone, Pune',
'Pune Shikrapur Eco Zone, Pune',
'Pune Koregaon Bhima Eco Zone, Pune',
'Pune Sanaswadi Eco Zone, Pune',
'Pune Lonikand Eco Zone, Pune',
'Pune Wagholi Eco Zone, Pune',
'Pune Chakan Green Zone, Pune',
'Pune Talegaon Green Zone, Pune',
'Pune Ranjangaon Green Zone, Pune',
'Pune Hinjawadi Green Zone, Pune',
'Pune Talawade Green Zone, Pune',
'Pune Baramati Green Zone, Pune',
'Pune Jejuri Green Zone, Pune',
'Pune Saswad Green Zone, Pune',
'Pune Purandar Green Zone, Pune',
'Pune Daund Green Zone, Pune',
'Pune Phaltan Green Zone, Pune',
'Pune Khed Green Zone, Pune',
'Pune Shikrapur Green Zone, Pune',
'Pune Koregaon Bhima Green Zone, Pune',
'Pune Sanaswadi Green Zone, Pune',
'Pune Lonikand Green Zone, Pune',
'Pune Wagholi Green Zone, Pune',
'Pune Chakan Residential Zone, Pune',
'Pune Talegaon Residential Zone, Pune',
'Pune Ranjangaon Residential Zone, Pune',
'Pune Hinjawadi Residential Zone, Pune',
'Pune Talawade Residential Zone, Pune',
'Pune Baramati Residential Zone, Pune',
'Pune Jejuri Residential Zone, Pune',
'Pune Saswad Residential Zone, Pune',
'Pune Purandar Residential Zone, Pune',
'Pune Daund Residential Zone, Pune',
'Pune Phaltan Residential Zone, Pune',
'Pune Khed Residential Zone, Pune',
'Pune Shikrapur Residential Zone, Pune',
'Pune Koregaon Bhima Residential Zone, Pune',
'Pune Sanaswadi Residential Zone, Pune',
'Pune Lonikand Residential Zone, Pune',
'Pune Wagholi Residential Zone, Pune',
'Pune Chakan Mixed-Use Zone, Pune',
'Pune Talegaon Mixed-Use Zone, Pune',
'Pune Ranjangaon Mixed-Use Zone, Pune',
'Pune Hinjawadi Mixed-Use Zone, Pune',
'Pune Talawade Mixed-Use Zone, Pune',
'Pune Baramati Mixed-Use Zone, Pune',
'Pune Jejuri Mixed-Use Zone, Pune',
'Pune Saswad Mixed-Use Zone, Pune',
'Pune Purandar Mixed-Use Zone, Pune',
'Pune Daund Mixed-Use Zone, Pune',
'Pune Phaltan Mixed-Use Zone, Pune',
'Pune Khed Mixed-Use Zone, Pune',
'Pune Shikrapur Mixed-Use Zone, Pune',
'Pune Koregaon Bhima Mixed-Use Zone, Pune',
'Pune Sanaswadi Mixed-Use Zone, Pune',
'Pune Lonikand Mixed-Use Zone, Pune',
'Pune Wagholi Mixed-Use Zone, Pune',
'Pune Chakan Urban Zone, Pune',
'Pune Talegaon Urban Zone, Pune',
'Pune Ranjangaon Urban Zone, Pune',
'Pune Hinjawadi Urban Zone, Pune',
'Pune Talawade Urban Zone, Pune',
'Pune Baramati Urban Zone, Pune',
'Pune Jejuri Urban Zone, Pune',
'Pune Saswad Urban Zone, Pune',
'Pune Purandar Urban Zone, Pune',
'Pune Daund Urban Zone, Pune',
'Pune Phaltan Urban Zone, Pune',
'Pune Khed Urban Zone, Pune',
'Pune Shikrapur Urban Zone, Pune',
'Pune Koregaon Bhima Urban Zone, Pune',
'Pune Sanaswadi Urban Zone, Pune',
'Pune Lonikand Urban Zone, Pune'
  ];
  
  export default places;
  